// Dữ liệu quỹ mở Việt Nam (Open-ended Mutual Funds Vietnam)

export type FundCategory = 'equity' | 'bond' | 'balanced'

export interface FundHolding {
  symbol: string
  name: string
  industry: string
  weight: number // % tỷ trọng danh mục
}

export interface Fund {
  id: string
  code: string // Mã CCQ: DCDS, VEOF, VCBF-MGF,...
  name: string
  category: FundCategory
  issuer: string // Dragon Capital, VinaCapital, VCBF, SSIAM,...
  nav: number // Giá NAV gần nhất (VND)
  navDate: string // Ngày cập nhật NAV (dd/MM/yyyy)
  ytdReturn: number // % Lợi nhuận từ đầu năm
  return1Y: number // % Lợi nhuận 1 năm
  return3Y: number // % Lợi nhuận 3 năm
  aumBillionVnd?: number // Quy mô tài sản (tỷ VNĐ)
  managementFee?: number // % Phí quản lý hàng năm
  inceptionDate?: string
  holdings: FundHolding[]
  description: string
}

export interface StockHoldingStats {
  rank: number
  symbol: string
  industry: string
  fundCount: number
  avgWeight: number
}

export interface IndustryHoldingStats {
  rank: number
  industry: string
  fundCount: number
  avgWeight: number
}

export const FUND_CATEGORIES: { key: FundCategory | 'all'; label: string }[] = [
  { key: 'all', label: 'Tất cả' },
  { key: 'equity', label: 'Cổ phiếu' },
  { key: 'bond', label: 'Trái phiếu' },
  { key: 'balanced', label: 'Cân bằng' },
]

export const FUND_ISSUERS = [
  'Tất cả tổ chức',
  'DRAGON CAPITAL',
  'VINACAPITAL',
  'VIETCOMBANK_FUND',
  'MIRAE_ASSET',
  'SSIAM',
  'IPAAM',
  'BAOVIET_FUND',
  'TECHCOM_CAPITAL',
  'MBCAPITAL',
  'ABF',
  'LPBA',
]

export const FUNDS_DATA: Fund[] = [
  {
    id: 'dcds',
    code: 'DCDS',
    name: 'Quỹ Đầu Tư Chứng Khoán Năng Động DC',
    category: 'equity',
    issuer: 'DRAGON CAPITAL',
    nav: 82450.12,
    navDate: '28/08/2026',
    ytdReturn: 16.82,
    return1Y: 28.45,
    return3Y: 46.12,
    aumBillionVnd: 7850,
    managementFee: 1.8,
    inceptionDate: '20/05/2004',
    description: 'Quỹ mở cổ phiếu đầu tiên tại Việt Nam, tập trung vào các doanh nghiệp tăng trưởng đầu ngành và định giá hấp dẫn.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 8.9 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 8.1 },
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 7.5 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 6.8 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 5.9 },
      { symbol: 'STB', name: 'Sacombank', industry: 'Ngân hàng', weight: 5.2 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 4.8 },
      { symbol: 'VHM', name: 'Vinhomes', industry: 'Bất động sản', weight: 4.5 },
      { symbol: 'KDH', name: 'Nhà Khang Điền', industry: 'Bất động sản', weight: 4.1 },
      { symbol: 'VND', name: 'Chứng khoán VNDIRECT', industry: 'Chứng khoán', weight: 3.8 },
    ],
  },
  {
    id: 'veof',
    code: 'VEOF',
    name: 'Quỹ Đầu Tư Cổ Phiếu Hưng Thịnh VinaCapital',
    category: 'equity',
    issuer: 'VINACAPITAL',
    nav: 33420.45,
    navDate: '28/08/2026',
    ytdReturn: 18.25,
    return1Y: 31.10,
    return3Y: 52.80,
    aumBillionVnd: 5120,
    managementFee: 1.75,
    inceptionDate: '01/07/2014',
    description: 'Chiến lược đầu tư chủ động tập trung vào các cổ phiếu vốn hóa lớn và trung bình có tiềm năng tăng trưởng vượt trội.',
    holdings: [
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 9.4 },
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 8.2 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 7.6 },
      { symbol: 'ACB', name: 'Ngân hàng Á Châu', industry: 'Ngân hàng', weight: 7.1 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 6.3 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 5.8 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 5.4 },
      { symbol: 'GMD', name: 'Gemadept', industry: 'Cảng & Vận tải biển', weight: 4.9 },
      { symbol: 'VRE', name: 'Vincom Retail', industry: 'Bất động sản', weight: 4.2 },
      { symbol: 'MSN', name: 'Tập đoàn Masan', industry: 'Thực phẩm - Đồ uống', weight: 3.9 },
    ],
  },
  {
    id: 'vcbf-bcf',
    code: 'VCBF-BCF',
    name: 'Quỹ Đầu Tư Cổ Phiếu Hàng Đầu VCBF',
    category: 'equity',
    issuer: 'VIETCOMBANK_FUND',
    nav: 35820.60,
    navDate: '28/08/2026',
    ytdReturn: 15.60,
    return1Y: 27.80,
    return3Y: 48.90,
    aumBillionVnd: 4650,
    managementFee: 1.6,
    inceptionDate: '22/08/2014',
    description: 'Đầu tư vào các cổ phiếu hàng đầu có vị thế độc quyền hoặc lợi thế cạnh tranh bền vững tại thị trường Việt Nam.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 9.1 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 8.5 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 7.8 },
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 7.2 },
      { symbol: 'ACB', name: 'Ngân hàng Á Châu', industry: 'Ngân hàng', weight: 6.9 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 6.2 },
      { symbol: 'VCB', name: 'Vietcombank', industry: 'Ngân hàng', weight: 5.8 },
      { symbol: 'VHM', name: 'Vinhomes', industry: 'Bất động sản', weight: 4.8 },
      { symbol: 'VHC', name: 'Vĩnh Hoàn', industry: 'Nông - Lâm - Ngư', weight: 4.3 },
      { symbol: 'MSN', name: 'Tập đoàn Masan', industry: 'Thực phẩm - Đồ uống', weight: 3.9 },
    ],
  },
  {
    id: 'vcbf-mgf',
    code: 'VCBF-MGF',
    name: 'Quỹ Đầu Tư Cổ Phiếu Tăng Trưởng VCBF',
    category: 'equity',
    issuer: 'VIETCOMBANK_FUND',
    nav: 28450.30,
    navDate: '28/08/2026',
    ytdReturn: 17.40,
    return1Y: 29.80,
    return3Y: 49.30,
    aumBillionVnd: 3820,
    managementFee: 1.7,
    inceptionDate: '20/10/2021',
    description: 'Tìm kiếm cơ hội sinh lời vượt trội thông qua việc đầu tư vào các doanh nghiệp tăng trưởng nhanh trong nền kinh tế Việt Nam.',
    holdings: [
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 9.8 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 8.4 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 7.9 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 7.2 },
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 6.7 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 6.1 },
      { symbol: 'FRT', name: 'Bán lẻ FPT', industry: 'Bán lẻ', weight: 5.5 },
      { symbol: 'GMD', name: 'Gemadept', industry: 'Cảng & Vận tải biển', weight: 4.6 },
      { symbol: 'HAH', name: 'Vận tải Hải An', industry: 'Cảng & Vận tải biển', weight: 3.8 },
      { symbol: 'PNJ', name: 'Vàng bạc Phú Nhuận', industry: 'Bán lẻ', weight: 3.7 },
    ],
  },
  {
    id: 'vesaf',
    code: 'VESAF',
    name: 'Quỹ Đầu Tư Cổ Phiếu Tiếp Cận Thị Trường VinaCapital',
    category: 'equity',
    issuer: 'VINACAPITAL',
    nav: 38750.90,
    navDate: '28/08/2026',
    ytdReturn: 19.80,
    return1Y: 34.60,
    return3Y: 62.40,
    aumBillionVnd: 4100,
    managementFee: 1.8,
    inceptionDate: '18/04/2017',
    description: 'Tập trung vào các cổ phiếu vốn hóa vừa và nhỏ (Mid-cap & Small-cap) có tiềm năng tăng trưởng thần tốc và biên lợi nhuận cao.',
    holdings: [
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 9.5 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 8.1 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 7.8 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 6.9 },
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 6.4 },
      { symbol: 'GMD', name: 'Gemadept', industry: 'Cảng & Vận tải biển', weight: 5.5 },
      { symbol: 'KDH', name: 'Nhà Khang Điền', industry: 'Bất động sản', weight: 4.8 },
      { symbol: 'STB', name: 'Sacombank', industry: 'Ngân hàng', weight: 4.5 },
      { symbol: 'DGC', name: 'Hóa chất Đức Giang', industry: 'Sản xuất Nhựa - Hóa chất', weight: 4.2 },
      { symbol: 'NLG', name: 'Nam Long', industry: 'Bất động sản', weight: 3.9 },
    ],
  },
  {
    id: 'ssiam-vnlx',
    code: 'SSIAM-VNX50',
    name: 'Quỹ Đầu Tư Cổ Phiếu SSIAM VNX50',
    category: 'equity',
    issuer: 'SSIAM',
    nav: 24350.20,
    navDate: '28/08/2026',
    ytdReturn: 14.80,
    return1Y: 25.40,
    return3Y: 41.50,
    aumBillionVnd: 2950,
    managementFee: 1.5,
    inceptionDate: '15/09/2014',
    description: 'Mô phỏng và đầu tư trọng tâm vào rổ chỉ số 50 cổ phiếu hàng đầu thị trường chứng khoán Việt Nam.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 8.8 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 8.2 },
      { symbol: 'VPB', name: 'VPBank', industry: 'Ngân hàng', weight: 7.7 },
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 7.1 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 6.5 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 6.0 },
      { symbol: 'VHM', name: 'Vinhomes', industry: 'Bất động sản', weight: 5.3 },
      { symbol: 'MSN', name: 'Tập đoàn Masan', industry: 'Thực phẩm - Đồ uống', weight: 4.9 },
      { symbol: 'SSI', name: 'Chứng khoán SSI', industry: 'Chứng khoán', weight: 4.5 },
      { symbol: 'VCB', name: 'Vietcombank', industry: 'Ngân hàng', weight: 4.2 },
    ],
  },
  {
    id: 'mafeg',
    code: 'MAFEG',
    name: 'Quỹ Đầu Tư Cổ Phiếu Tăng Trưởng Mirae Asset Việt Nam',
    category: 'equity',
    issuer: 'MIRAE_ASSET',
    nav: 21650.75,
    navDate: '28/08/2026',
    ytdReturn: 15.20,
    return1Y: 26.80,
    return3Y: 43.10,
    aumBillionVnd: 2100,
    managementFee: 1.65,
    inceptionDate: '12/12/2019',
    description: 'Tận dụng kinh nghiệm toàn cầu của Tập đoàn Mirae Asset để tìm kiếm doanh nghiệp tăng trưởng dẫn đầu thị trường.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 8.7 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 8.0 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 7.6 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 6.9 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 6.5 },
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 6.1 },
      { symbol: 'VHM', name: 'Vinhomes', industry: 'Bất động sản', weight: 5.4 },
      { symbol: 'STB', name: 'Sacombank', industry: 'Ngân hàng', weight: 4.8 },
      { symbol: 'VCI', name: 'Chứng khoán Vietcap', industry: 'Chứng khoán', weight: 4.2 },
      { symbol: 'ACB', name: 'Ngân hàng Á Châu', industry: 'Ngân hàng', weight: 4.0 },
    ],
  },
  {
    id: 'dcbc',
    code: 'DCBC',
    name: 'Quỹ Đầu Tư Doanh Nghiệp Hàng Đầu DC',
    category: 'equity',
    issuer: 'DRAGON CAPITAL',
    nav: 44210.30,
    navDate: '28/08/2026',
    ytdReturn: 16.10,
    return1Y: 27.90,
    return3Y: 45.30,
    aumBillionVnd: 3450,
    managementFee: 1.7,
    inceptionDate: '29/07/2008',
    description: 'Tập trung đầu tư vào các doanh nghiệp niêm yết có năng lực quản trị xuất sắc và dòng tiền kinh doanh lành mạnh.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 9.3 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 8.6 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 7.9 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 7.1 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 6.4 },
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 6.0 },
      { symbol: 'VCB', name: 'Vietcombank', industry: 'Ngân hàng', weight: 5.3 },
      { symbol: 'VHM', name: 'Vinhomes', industry: 'Bất động sản', weight: 4.7 },
      { symbol: 'MSN', name: 'Tập đoàn Masan', industry: 'Thực phẩm - Đồ uống', weight: 4.1 },
      { symbol: 'KDH', name: 'Nhà Khang Điền', industry: 'Bất động sản', weight: 3.6 },
    ],
  },

  // Quỹ Trái phiếu (Bond funds)
  {
    id: 'vcbf-fif',
    code: 'VCBF-FIF',
    name: 'Quỹ Đầu Tư Trái Phiếu VCBF',
    category: 'bond',
    issuer: 'VIETCOMBANK_FUND',
    nav: 16123.50,
    navDate: '27/08/2026',
    ytdReturn: 5.07,
    return1Y: 8.45,
    return3Y: 23.72,
    aumBillionVnd: 2890,
    managementFee: 0.9,
    inceptionDate: '09/08/2019',
    description: 'Chiến lược bảo toàn vốn và tạo thu nhập định kỳ ổn định thông qua danh mục trái phiếu doanh nghiệp chất lượng cao và trái phiếu chính phủ.',
    holdings: [
      { symbol: 'TP-VIC', name: 'Trái phiếu Vingroup', industry: 'Bất động sản', weight: 14.5 },
      { symbol: 'TP-MSN', name: 'Trái phiếu Masan Group', industry: 'Thực phẩm - Đồ uống', weight: 13.2 },
      { symbol: 'TP-NVL', name: 'Trái phiếu Novaland', industry: 'Bất động sản', weight: 8.6 },
      { symbol: 'TP-GELEX', name: 'Trái phiếu Gelex', industry: 'Thiết bị điện & Năng lượng', weight: 8.1 },
      { symbol: 'TP-TCB', name: 'Trái phiếu Techcombank', industry: 'Ngân hàng', weight: 7.9 },
    ],
  },
  {
    id: 'maff',
    code: 'MAFF',
    name: 'Quỹ Đầu Tư Trái Phiếu Mirae Asset Việt Nam',
    category: 'bond',
    issuer: 'MIRAE_ASSET',
    nav: 13969.80,
    navDate: '28/08/2026',
    ytdReturn: 5.00,
    return1Y: 8.60,
    return3Y: 24.07,
    aumBillionVnd: 1850,
    managementFee: 0.85,
    inceptionDate: '15/10/2020',
    description: 'Đầu tư an toàn vào các công cụ có thu nhập cố định, chứng chỉ tiền gửi ngân hàng và trái phiếu doanh nghiệp xếp hạng tín nhiệm cao.',
    holdings: [
      { symbol: 'TP-MBB', name: 'Trái phiếu MBBank', industry: 'Ngân hàng', weight: 15.2 },
      { symbol: 'TP-BIDV', name: 'Trái phiếu BIDV', industry: 'Ngân hàng', weight: 14.8 },
      { symbol: 'TP-REE', name: 'Trái phiếu REE Corp', industry: 'Năng lượng & Cơ điện', weight: 11.3 },
      { symbol: 'TP-VHM', name: 'Trái phiếu Vinhomes', industry: 'Bất động sản', weight: 9.7 },
    ],
  },
  {
    id: 'abbf',
    code: 'ABBF',
    name: 'Quỹ Đầu Tư Trái Phiếu An Bình',
    category: 'bond',
    issuer: 'ABF',
    nav: 14581.10,
    navDate: '28/08/2026',
    ytdReturn: 4.80,
    return1Y: 8.20,
    return3Y: 20.12,
    aumBillionVnd: 1200,
    managementFee: 0.8,
    inceptionDate: '10/05/2018',
    description: 'Bảo toàn tài sản cho nhà đầu tư với danh mục trái phiếu an toàn, thanh khoản cao.',
    holdings: [
      { symbol: 'TP-VCB', name: 'Trái phiếu Vietcombank', industry: 'Ngân hàng', weight: 18.5 },
      { symbol: 'TP-CTG', name: 'Trái phiếu VietinBank', industry: 'Ngân hàng', weight: 16.2 },
      { symbol: 'TP-VND', name: 'Trái phiếu VNDIRECT', industry: 'Chứng khoán', weight: 10.4 },
    ],
  },
  {
    id: 'vff',
    code: 'VFF',
    name: 'Quỹ Đầu Tư Trái Phiếu Bảo Thịnh VinaCapital',
    category: 'bond',
    issuer: 'VINACAPITAL',
    nav: 26735.40,
    navDate: '27/08/2026',
    ytdReturn: 4.75,
    return1Y: 8.15,
    return3Y: 23.37,
    aumBillionVnd: 2430,
    managementFee: 0.95,
    inceptionDate: '01/04/2013',
    description: 'Một trong những quỹ trái phiếu uy tín nhất Việt Nam với lịch sử sinh lời ổn định và quản trị rủi ro khắt khe.',
    holdings: [
      { symbol: 'TP-MSN', name: 'Trái phiếu Masan Consumer', industry: 'Thực phẩm - Đồ uống', weight: 16.8 },
      { symbol: 'TP-VIC', name: 'Trái phiếu Vingroup', industry: 'Bất động sản', weight: 12.5 },
      { symbol: 'TP-TCB', name: 'Trái phiếu Techcombank', industry: 'Ngân hàng', weight: 11.2 },
      { symbol: 'TP-KBC', name: 'Trái phiếu Kinh Bắc', industry: 'Bất động sản', weight: 8.3 },
    ],
  },
  {
    id: 'lpbf',
    code: 'LPBF',
    name: 'Quỹ Đầu Tư Trái Phiếu LPBank',
    category: 'bond',
    issuer: 'LPBA',
    nav: 10778.20,
    navDate: '28/08/2026',
    ytdReturn: 4.69,
    return1Y: 7.95,
    return3Y: 18.50,
    aumBillionVnd: 980,
    managementFee: 0.8,
    inceptionDate: '12/03/2022',
    description: 'Danh mục tập trung vào tiền gửi kỳ hạn và trái phiếu ngân hàng, rủi ro biến động cực thấp.',
    holdings: [
      { symbol: 'TP-LPB', name: 'Trái phiếu LPBank', industry: 'Ngân hàng', weight: 22.0 },
      { symbol: 'TP-BIDV', name: 'Trái phiếu BIDV', industry: 'Ngân hàng', weight: 18.4 },
      { symbol: 'TP-CTG', name: 'Trái phiếu VietinBank', industry: 'Ngân hàng', weight: 14.1 },
    ],
  },
  {
    id: 'dcbf',
    code: 'DCBF',
    name: 'Quỹ Đầu Tư Trái Phiếu DC',
    category: 'bond',
    issuer: 'DRAGON CAPITAL',
    nav: 28410.60,
    navDate: '28/08/2026',
    ytdReturn: 4.88,
    return1Y: 8.30,
    return3Y: 22.90,
    aumBillionVnd: 2650,
    managementFee: 0.9,
    inceptionDate: '24/12/2013',
    description: 'Quỹ mở trái phiếu của Dragon Capital, tối ưu lợi tức thu nhập cố định vượt lãi suất ngân hàng.',
    holdings: [
      { symbol: 'TP-VHM', name: 'Trái phiếu Vinhomes', industry: 'Bất động sản', weight: 15.8 },
      { symbol: 'TP-MSN', name: 'Trái phiếu Masan Group', industry: 'Thực phẩm - Đồ uống', weight: 14.2 },
      { symbol: 'TP-MBB', name: 'Trái phiếu MBBank', industry: 'Ngân hàng', weight: 12.6 },
    ],
  },

  // Quỹ Cân bằng (Balanced funds)
  {
    id: 'vcbf-tbf',
    code: 'VCBF-TBF',
    name: 'Quỹ Đầu Tư Cân Bằng Chiến Lược VCBF',
    category: 'balanced',
    issuer: 'VIETCOMBANK_FUND',
    nav: 32150.80,
    navDate: '28/08/2026',
    ytdReturn: 10.45,
    return1Y: 18.30,
    return3Y: 36.40,
    aumBillionVnd: 1980,
    managementFee: 1.4,
    inceptionDate: '24/12/2013',
    description: 'Phân bổ linh hoạt 50% cổ phiếu và 50% trái phiếu, cân bằng hài hòa giữa tăng trưởng và phòng thủ rủi ro.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 6.2 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 5.8 },
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 5.1 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 4.5 },
      { symbol: 'TP-BIDV', name: 'Trái phiếu BIDV', industry: 'Ngân hàng', weight: 8.5 },
      { symbol: 'TP-VCB', name: 'Trái phiếu Vietcombank', industry: 'Ngân hàng', weight: 7.9 },
    ],
  },
  {
    id: 'vibf',
    code: 'VIBF',
    name: 'Quỹ Đầu Tư Cân Bằng Tuệ Sáng VinaCapital',
    category: 'balanced',
    issuer: 'VINACAPITAL',
    nav: 22680.40,
    navDate: '28/08/2026',
    ytdReturn: 11.20,
    return1Y: 19.50,
    return3Y: 38.70,
    aumBillionVnd: 1650,
    managementFee: 1.45,
    inceptionDate: '02/07/2019',
    description: 'Chiến lược phân bổ tài sản linh hoạt theo chu kỳ kinh tế, giảm thiểu biến động thị trường.',
    holdings: [
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 6.5 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 5.9 },
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 5.4 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 4.8 },
      { symbol: 'TP-MSN', name: 'Trái phiếu Masan Consumer', industry: 'Thực phẩm - Đồ uống', weight: 8.2 },
    ],
  },
  {
    id: 'ssiam-bca',
    code: 'SSIAM-BCA',
    name: 'Quỹ Đầu Tư Cân Bằng SSIAM',
    category: 'balanced',
    issuer: 'SSIAM',
    nav: 19450.90,
    navDate: '28/08/2026',
    ytdReturn: 9.80,
    return1Y: 17.10,
    return3Y: 33.50,
    aumBillionVnd: 1120,
    managementFee: 1.35,
    inceptionDate: '10/01/2020',
    description: 'Kết hợp tỷ trọng cổ phiếu bluechip và trái phiếu doanh nghiệp hàng đầu để tạo ra dòng tiền bền vững.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 5.9 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 5.3 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 4.7 },
      { symbol: 'TP-CTG', name: 'Trái phiếu VietinBank', industry: 'Ngân hàng', weight: 8.0 },
    ],
  },
  {
    id: 'bvfed',
    code: 'BVFED',
    name: 'Quỹ Đầu Tư Cổ Phiếu Năng Động Bảo Việt',
    category: 'equity',
    issuer: 'BAOVIET_FUND',
    nav: 23140.50,
    navDate: '28/08/2026',
    ytdReturn: 14.30,
    return1Y: 24.80,
    return3Y: 39.70,
    aumBillionVnd: 1850,
    managementFee: 1.6,
    inceptionDate: '15/01/2014',
    description: 'Quỹ mở cổ phiếu của Bảo Việt Fund, tập trung vào doanh nghiệp tăng trưởng dài hạn và trả cổ tức đều.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 8.4 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 7.7 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 7.2 },
      { symbol: 'VCB', name: 'Vietcombank', industry: 'Ngân hàng', weight: 6.4 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 5.8 },
      { symbol: 'VHM', name: 'Vinhomes', industry: 'Bất động sản', weight: 5.1 },
      { symbol: 'MSN', name: 'Tập đoàn Masan', industry: 'Thực phẩm - Đồ uống', weight: 4.5 },
    ],
  },
  {
    id: 'tceat',
    code: 'TCEAT',
    name: 'Quỹ Đầu Tư Cổ Phiếu Tăng Trưởng Techcom',
    category: 'equity',
    issuer: 'TECHCOM_CAPITAL',
    nav: 18940.20,
    navDate: '28/08/2026',
    ytdReturn: 15.90,
    return1Y: 27.20,
    return3Y: 42.60,
    aumBillionVnd: 2340,
    managementFee: 1.6,
    inceptionDate: '18/09/2015',
    description: 'Tận dụng hệ sinh thái tài chính Techcombank để lựa chọn các cổ phiếu dẫn dắt xu hướng tiêu dùng và tài chính.',
    holdings: [
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 9.6 },
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 8.5 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 7.8 },
      { symbol: 'MSN', name: 'Tập đoàn Masan', industry: 'Thực phẩm - Đồ uống', weight: 6.9 },
      { symbol: 'VHM', name: 'Vinhomes', industry: 'Bất động sản', weight: 6.0 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 5.4 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 4.9 },
    ],
  },
  {
    id: 'mbvf',
    code: 'MBVF',
    name: 'Quỹ Đầu Tư Giá Trị MB Capital',
    category: 'equity',
    issuer: 'MBCAPITAL',
    nav: 19820.60,
    navDate: '28/08/2026',
    ytdReturn: 14.50,
    return1Y: 25.10,
    return3Y: 40.80,
    aumBillionVnd: 1540,
    managementFee: 1.6,
    inceptionDate: '25/04/2014',
    description: 'Tìm kiếm các doanh nghiệp có mức định giá thấp hơn giá trị thực tế và tỷ lệ cổ tức hấp dẫn.',
    holdings: [
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 9.4 },
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 8.2 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 7.5 },
      { symbol: 'ACB', name: 'Ngân hàng Á Châu', industry: 'Ngân hàng', weight: 6.8 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 6.1 },
      { symbol: 'VHM', name: 'Vinhomes', industry: 'Bất động sản', weight: 5.2 },
      { symbol: 'STB', name: 'Sacombank', industry: 'Ngân hàng', weight: 4.6 },
    ],
  },
  {
    id: 'vmeef',
    code: 'VMEEF',
    name: 'Quỹ Đầu Tư Cổ Phiếu Kinh Tế Hiện Đại VinaCapital',
    category: 'equity',
    issuer: 'VINACAPITAL',
    nav: 17450.30,
    navDate: '28/08/2026',
    ytdReturn: 17.90,
    return1Y: 30.50,
    return3Y: 50.10,
    aumBillionVnd: 2800,
    managementFee: 1.75,
    inceptionDate: '04/05/2023',
    description: 'Tập trung đầu tư vào các doanh nghiệp hưởng lợi từ tăng trưởng kinh tế dài hạn, quá trình số hóa và tiêu dùng hiện đại.',
    holdings: [
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 9.7 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 8.8 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 7.6 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 7.2 },
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 6.8 },
      { symbol: 'GMD', name: 'Gemadept', industry: 'Cảng & Vận tải biển', weight: 5.4 },
      { symbol: 'FRT', name: 'Bán lẻ FPT', industry: 'Bán lẻ', weight: 4.8 },
    ],
  },
  {
    id: 'vlbf',
    code: 'VLBF',
    name: 'Quỹ Đầu Tư Trái Phiếu Bảo Toàn VinaCapital',
    category: 'bond',
    issuer: 'VINACAPITAL',
    nav: 12450.60,
    navDate: '28/08/2026',
    ytdReturn: 4.90,
    return1Y: 8.35,
    return3Y: 22.50,
    aumBillionVnd: 1420,
    managementFee: 0.85,
    inceptionDate: '10/06/2021',
    description: 'Quỹ trái phiếu ngắn hạn mang tính thanh khoản cao, phù hợp cho nhà đầu tư cần gửi tiền sinh lời tối ưu hơn tiết kiệm.',
    holdings: [
      { symbol: 'TP-MBB', name: 'Trái phiếu MBBank', industry: 'Ngân hàng', weight: 16.5 },
      { symbol: 'TP-TCB', name: 'Trái phiếu Techcombank', industry: 'Ngân hàng', weight: 15.2 },
      { symbol: 'TP-VCB', name: 'Trái phiếu Vietcombank', industry: 'Ngân hàng', weight: 14.8 },
    ],
  },
  {
    id: 'ssiam-caif',
    code: 'SSIAM-CAIF',
    name: 'Quỹ Đầu Tư Cổ Phiếu Tăng Trưởng SSIAM CAIF',
    category: 'equity',
    issuer: 'SSIAM',
    nav: 22180.40,
    navDate: '28/08/2026',
    ytdReturn: 16.40,
    return1Y: 28.10,
    return3Y: 44.70,
    aumBillionVnd: 2150,
    managementFee: 1.7,
    inceptionDate: '18/06/2019',
    description: 'Lựa chọn các cổ phiếu vốn hóa lớn và vừa có lợi thế kinh doanh độc tôn và định giá hấp dẫn.',
    holdings: [
      { symbol: 'HPG', name: 'Tập đoàn Hòa Phát', industry: 'Vật liệu xây dựng', weight: 9.0 },
      { symbol: 'TCB', name: 'Techcombank', industry: 'Ngân hàng', weight: 8.1 },
      { symbol: 'CTG', name: 'VietinBank', industry: 'Ngân hàng', weight: 7.4 },
      { symbol: 'MWG', name: 'Thế Giới Di Động', industry: 'Bán lẻ', weight: 6.8 },
      { symbol: 'FPT', name: 'Tập đoàn FPT', industry: 'Công nghệ và thông tin', weight: 6.5 },
      { symbol: 'MBB', name: 'Ngân hàng Quân Đội', industry: 'Ngân hàng', weight: 5.9 },
    ],
  },
]

// Thống kê Top 10 cổ phiếu được quỹ nắm giữ nhiều nhất
export const TOP_STOCK_HOLDINGS: StockHoldingStats[] = [
  { rank: 1, symbol: 'HPG', industry: 'Vật liệu xây dựng', fundCount: 33, avgWeight: 5.65 },
  { rank: 2, symbol: 'CTG', industry: 'Ngân hàng', fundCount: 31, avgWeight: 4.76 },
  { rank: 3, symbol: 'MWG', industry: 'Bán lẻ', fundCount: 31, avgWeight: 4.42 },
  { rank: 4, symbol: 'MBB', industry: 'Ngân hàng', fundCount: 28, avgWeight: 5.92 },
  { rank: 5, symbol: 'TCB', industry: 'Ngân hàng', fundCount: 23, avgWeight: 4.67 },
  { rank: 6, symbol: 'VCB', industry: 'Ngân hàng', fundCount: 20, avgWeight: 4.48 },
  { rank: 7, symbol: 'ACB', industry: 'Ngân hàng', fundCount: 18, avgWeight: 6.47 },
  { rank: 8, symbol: 'VHM', industry: 'Bất động sản', fundCount: 15, avgWeight: 5.21 },
  { rank: 9, symbol: 'STB', industry: 'Ngân hàng', fundCount: 14, avgWeight: 4.36 },
  { rank: 10, symbol: 'MSN', industry: 'Thực phẩm - Đồ uống', fundCount: 12, avgWeight: 4.00 },
]

// Thống kê Top 10 ngành được phân bổ nhiều nhất
export const TOP_INDUSTRY_HOLDINGS: IndustryHoldingStats[] = [
  { rank: 1, industry: 'Ngân hàng', fundCount: 40, avgWeight: 26.82 },
  { rank: 2, industry: 'Bất động sản', fundCount: 37, avgWeight: 11.65 },
  { rank: 3, industry: 'Vật liệu xây dựng', fundCount: 37, avgWeight: 5.79 },
  { rank: 4, industry: 'Thực phẩm - Đồ uống', fundCount: 37, avgWeight: 5.76 },
  { rank: 5, industry: 'Chứng khoán', fundCount: 38, avgWeight: 4.65 },
  { rank: 6, industry: 'Bán lẻ', fundCount: 38, avgWeight: 4.59 },
  { rank: 7, industry: 'Nông - Lâm - Ngư', fundCount: 15, avgWeight: 4.05 },
  { rank: 8, industry: 'Sản xuất Nhựa - Hóa chất', fundCount: 30, avgWeight: 4.04 },
  { rank: 9, industry: 'Công nghệ và thông tin', fundCount: 28, avgWeight: 4.04 },
  { rank: 10, industry: 'Cảng & Vận tải biển', fundCount: 32, avgWeight: 3.68 },
]
