export type TierAStock = {
  ticker: string
  name: string
  exchange: 'HOSE' | 'HNX' | 'UPCOM'
  groupId: 'det-may' | 'phan-bon' | 'sat-thep' | 'cao-su' | 'thuy-san' | 'khac'
  groupLabel: string
  customsCommodities: string[]
  tradeDirection: 'EXPORT' | 'IMPORT' | 'BOTH'
  correlationR?: number // Hệ số tương quan Pearson với kim ngạch XNK TCHQ
  yearsTracked?: number // Số năm kiểm chứng dữ liệu
  description: string
  keyMarkets?: string[] // Thị trường xuất nhập khẩu trọng điểm
}

export type TierAGroup = {
  id: string
  label: string
  count: number
  description: string
  customsCommodities: string[]
  avgR?: number
}

export const TIER_A_GROUPS: TierAGroup[] = [
  {
    id: 'det-may',
    label: 'Dệt may',
    count: 21,
    description: 'Doanh nghiệp sản xuất may mặc, xơ sợi, dệt nhuộm và xuất khẩu hàng dệt may.',
    customsCommodities: ['Hàng dệt, may', 'Xơ, sợi dệt các loại', 'Vải các loại', 'Bông các loại'],
    avgR: 0.81,
  },
  {
    id: 'phan-bon',
    label: 'Phân bón & Hóa chất',
    count: 11,
    description: 'Doanh nghiệp sản xuất phân bón (Ure, NPK, DAP) và hóa chất công nghiệp cơ bản.',
    customsCommodities: ['Phân bón các loại', 'Hóa chất', 'Sản phẩm hóa chất', 'Phân Ure', 'Phân NPK', 'Phân DAP'],
    avgR: 0.78,
  },
  {
    id: 'sat-thep',
    label: 'Sắt thép & Kim loại',
    count: 10,
    description: 'Doanh nghiệp sản xuất và thương mại thép xây dựng, HRC, tôn mạ và phôi thép.',
    customsCommodities: ['Sắt thép các loại', 'Sản phẩm từ sắt thép', 'Phôi thép', 'Sắt thép phế liệu'],
    avgR: 0.86,
  },
  {
    id: 'cao-su',
    label: 'Cao su',
    count: 8,
    description: 'Doanh nghiệp trồng cây cao su, khai thác và chế biến mủ cao su xuất khẩu.',
    customsCommodities: ['Cao su', 'Sản phẩm từ cao su'],
    avgR: 0.72,
  },
  {
    id: 'thuy-san',
    label: 'Thủy sản',
    count: 7,
    description: 'Doanh nghiệp nuôi trồng, chế biến và xuất khẩu tôm, cá tra, hải sản đông lạnh.',
    customsCommodities: ['Thủy sản'],
    avgR: 0.83,
  },
  {
    id: 'khac',
    label: 'Ngành khác (Gỗ, Gạo, Nhựa, Gốm)',
    count: 4,
    description: 'Các nhóm ngành hàng xuất khẩu đơn lẻ có doanh nghiệp niêm yết quy mô đại diện.',
    customsCommodities: ['Gỗ và sản phẩm gỗ', 'Gạo', 'Chất dẻo nguyên liệu (nhựa)', 'Sản phẩm từ chất dẻo', 'Sản phẩm gốm, sứ'],
    avgR: 0.75,
  },
]

export const TIER_A_STOCKS: TierAStock[] = [
  // --- 1. THỦY SẢN (7 mã) ---
  {
    ticker: 'VHC',
    name: 'Công ty Cổ phần Vĩnh Hoàn',
    exchange: 'HOSE',
    groupId: 'thuy-san',
    groupLabel: 'Thủy sản',
    customsCommodities: ['Thủy sản'],
    tradeDirection: 'EXPORT',
    correlationR: 0.84,
    yearsTracked: 16,
    description: 'Doanh nghiệp đầu ngành chế biến và xuất khẩu cá tra fillet sang thị trường Mỹ, EU và Trung Quốc. Doanh thu phản ánh trực tiếp theo kim ngạch xuất khẩu thủy sản TCHQ.',
    keyMarkets: ['Hoa Kỳ', 'EU', 'Trung Quốc'],
  },
  {
    ticker: 'MPC',
    name: 'Công ty Cổ phần Tập đoàn Thủy sản Minh Phú',
    exchange: 'UPCOM',
    groupId: 'thuy-san',
    groupLabel: 'Thủy sản',
    customsCommodities: ['Thủy sản'],
    tradeDirection: 'EXPORT',
    correlationR: 0.82,
    yearsTracked: 16,
    description: 'Vua tôm Việt Nam với chuỗi giá trị khép kín, xuất khẩu tôm đông lạnh quy mô lớn sang Bắc Mỹ, Nhật Bản và châu Âu.',
    keyMarkets: ['Hoa Kỳ', 'Nhật Bản', 'EU', 'Úc'],
  },
  {
    ticker: 'AAM',
    name: 'Công ty Cổ Phần Thủy Sản MeKong',
    exchange: 'HOSE',
    groupId: 'thuy-san',
    groupLabel: 'Thủy sản',
    customsCommodities: ['Thủy sản'],
    tradeDirection: 'EXPORT',
    correlationR: 0.76,
    yearsTracked: 15,
    description: 'Chuyên chế biến, bảo quản và xuất khẩu các mặt hàng thủy hải sản đông lạnh (cá tra, cá basa, mực, nghêu).',
    keyMarkets: ['Châu Âu', 'Hàn Quốc', 'Nhật Bản'],
  },
  {
    ticker: 'CAT',
    name: 'Công ty Cổ phần Thủy sản Cà Mau',
    exchange: 'HNX',
    groupId: 'thuy-san',
    groupLabel: 'Thủy sản',
    customsCommodities: ['Thủy sản'],
    tradeDirection: 'EXPORT',
    correlationR: 0.74,
    yearsTracked: 14,
    description: 'Sản xuất và chế biến tôm xuất khẩu tại vùng nguyên liệu Cà Mau, nhạy cảm với biến động giá tôm nguyên liệu và kim ngạch xuất khẩu sang EU.',
    keyMarkets: ['EU', 'Nhật Bản', 'Hàn Quốc'],
  },
  {
    ticker: 'KHS',
    name: 'Công ty Cổ phần Kiên Hùng',
    exchange: 'UPCOM',
    groupId: 'thuy-san',
    groupLabel: 'Thủy sản',
    customsCommodities: ['Thủy sản'],
    tradeDirection: 'EXPORT',
    correlationR: 0.71,
    yearsTracked: 12,
    description: 'Chế biến thủy sản đông lạnh (mực, bạch tuộc, surimi) và bột cá xuất khẩu tại Kiên Giang.',
    keyMarkets: ['Nhật Bản', 'Hàn Quốc', 'ASEAN'],
  },
  {
    ticker: 'SEA',
    name: 'Tổng Công ty Thủy sản Việt Nam - CTCP (SEAPRODEX)',
    exchange: 'UPCOM',
    groupId: 'thuy-san',
    groupLabel: 'Thủy sản',
    customsCommodities: ['Thủy sản'],
    tradeDirection: 'BOTH',
    correlationR: 0.73,
    yearsTracked: 16,
    description: 'Tổng công ty thủy sản quy mô nhà nước, sở hữu danh mục đầu tư sâu rộng vào chuỗi chế biến, kho lạnh và thương mại thủy hải sản quốc tế.',
    keyMarkets: ['Toàn cầu'],
  },
  {
    ticker: 'THP',
    name: 'Công ty Cổ phần Thủy sản và Thương mại Thuận Phước',
    exchange: 'UPCOM',
    groupId: 'thuy-san',
    groupLabel: 'Thủy sản',
    customsCommodities: ['Thủy sản'],
    tradeDirection: 'EXPORT',
    correlationR: 0.75,
    yearsTracked: 15,
    description: 'Chế biến và xuất khẩu tôm cao cấp, các sản phẩm giá trị gia tăng sang thị trường Mỹ, Nhật Bản và EU.',
    keyMarkets: ['Hoa Kỳ', 'Nhật Bản', 'EU'],
  },

  // --- 2. DỆT MAY (21 mã) ---
  {
    ticker: 'TNG',
    name: 'Công ty Cổ phần Đầu tư và Thương mại TNG',
    exchange: 'HNX',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.85,
    yearsTracked: 16,
    description: 'Một trong những doanh nghiệp may xuất khẩu hàng đầu sang Mỹ và EU (đối tác lớn Decathlon, Columbia, The Children’s Place). Doanh thu bám sát số liệu xuất khẩu dệt may.',
    keyMarkets: ['Hoa Kỳ', 'Pháp (EU)', 'Canada', 'Nga'],
  },
  {
    ticker: 'MSH',
    name: 'Công ty Cổ phần May Sông Hồng',
    exchange: 'HOSE',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.83,
    yearsTracked: 16,
    description: 'Doanh nghiệp may mặc xuất khẩu hàng đầu tại Nam Định với tỷ trọng đơn hàng FOB/ODM cao, đối tác lớn của Columbia, Target, Walmart.',
    keyMarkets: ['Hoa Kỳ', 'EU', 'Nhật Bản'],
  },
  {
    ticker: 'TCM',
    name: 'Công ty Cổ phần Dệt may - Đầu tư - Thương mại Thành Công',
    exchange: 'HOSE',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may', 'Xơ, sợi dệt các loại'],
    tradeDirection: 'EXPORT',
    correlationR: 0.82,
    yearsTracked: 16,
    description: 'Sở hữu chuỗi cung ứng khép kín từ Sợi - Dệt - Nhuộm - May, xuất khẩu sang Hàn Quốc, Mỹ, Nhật Bản.',
    keyMarkets: ['Hàn Quốc', 'Hoa Kỳ', 'Nhật Bản'],
  },
  {
    ticker: 'STK',
    name: 'Công ty Cổ phần Sợi Thế Kỷ',
    exchange: 'HOSE',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Xơ, sợi dệt các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.80,
    yearsTracked: 15,
    description: 'Sản xuất sợi filament polyester nguyên sinh và tái chế (Recycle), là mắt xích đầu vào cốt lõi của ngành dệt may xuất khẩu.',
    keyMarkets: ['Việt Nam', 'Thái Lan', 'Hàn Quốc', 'Nhật Bản'],
  },
  {
    ticker: 'VGT',
    name: 'Tập đoàn Dệt May Việt Nam (VINATEX)',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may', 'Xơ, sợi dệt các loại', 'Vải các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.86,
    yearsTracked: 16,
    description: 'Tập đoàn dệt may lớn nhất Việt Nam, chi phối hệ thống sản xuất và kim ngạch xuất khẩu toàn ngành dệt may.',
    keyMarkets: ['Hoa Kỳ', 'EU', 'Nhật Bản', 'Hàn Quốc', 'Trung Quốc'],
  },
  {
    ticker: 'ADS',
    name: 'Công ty Cổ phần DAMSAN',
    exchange: 'HOSE',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Xơ, sợi dệt các loại', 'Bông các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.77,
    yearsTracked: 14,
    description: 'Sản xuất sợi cotton xuất khẩu chủ yếu sang thị trường Trung Quốc và dệt khăn bông cao cấp sang Nhật Bản.',
    keyMarkets: ['Trung Quốc', 'Nhật Bản'],
  },
  {
    ticker: 'BDG',
    name: 'Công ty Cổ phần May mặc Bình Dương',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.78,
    yearsTracked: 15,
    description: 'Gia công và sản xuất trang phục may mặc xuất khẩu sang thị trường Bắc Mỹ và châu Âu.',
    keyMarkets: ['Hoa Kỳ', 'EU'],
  },
  {
    ticker: 'BMG',
    name: 'Công ty Cổ phần May Bình Minh',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.74,
    yearsTracked: 13,
    description: 'Sản xuất và gia công các sản phẩm may mặc xuất khẩu truyền thống.',
    keyMarkets: ['Hoa Kỳ', 'Nhật Bản'],
  },
  {
    ticker: 'BVN',
    name: 'Công ty Cổ phần Bông Việt Nam',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Bông các loại', 'Xơ, sợi dệt các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.72,
    yearsTracked: 12,
    description: 'Kinh doanh, chế biến bông xơ nguyên liệu phục vụ chuỗi cung ứng dệt may trong nước và xuất khẩu.',
    keyMarkets: ['Việt Nam', 'Đông Nam Á'],
  },
  {
    ticker: 'GMC',
    name: 'Công ty Cổ phần Garmex Sài Gòn',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.76,
    yearsTracked: 16,
    description: 'Doanh nghiệp may mặc xuất khẩu truyền thống với thị trường chính là Mỹ và châu Âu.',
    keyMarkets: ['Hoa Kỳ', 'EU'],
  },
  {
    ticker: 'HDM',
    name: 'Công ty Cổ phần Dệt May Huế',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may', 'Xơ, sợi dệt các loại'],
    tradeDirection: 'EXPORT',
    correlationR: 0.79,
    yearsTracked: 15,
    description: 'Sản xuất và kinh doanh sợi, hàng dệt kim và may mặc xuất khẩu tại khu vực miền Trung.',
    keyMarkets: ['Hoa Kỳ', 'Nhật Bản'],
  },
  {
    ticker: 'HNI',
    name: 'Công ty Cổ phần May Hữu Nghị',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.73,
    yearsTracked: 13,
    description: 'Sản xuất trang phục may mặc xuất khẩu cho các đối tác quốc tế.',
    keyMarkets: ['Hoa Kỳ', 'EU'],
  },
  {
    ticker: 'HSM',
    name: 'Tổng Công ty Cổ phần Dệt May Hà Nội (Hanosimex)',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may', 'Xơ, sợi dệt các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.78,
    yearsTracked: 16,
    description: 'Doanh nghiệp kỳ cựu ngành dệt may miền Bắc với chuỗi sản xuất sợi, vải dệt kim và quần áo may mặc.',
    keyMarkets: ['Nhật Bản', 'Hoa Kỳ', 'Hàn Quốc'],
  },
  {
    ticker: 'HTG',
    name: 'Tổng Công ty Cổ phần Dệt may Hòa Thọ',
    exchange: 'HOSE',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may', 'Xơ, sợi dệt các loại'],
    tradeDirection: 'EXPORT',
    correlationR: 0.81,
    yearsTracked: 15,
    description: 'Doanh nghiệp xuất khẩu may mặc veston và sợi hàng đầu miền Trung, đơn hàng xuất khẩu chiếm trên 85% doanh thu.',
    keyMarkets: ['Hoa Kỳ', 'Nhật Bản', 'EU', 'Hàn Quốc'],
  },
  {
    ticker: 'HUG',
    name: 'Tổng công ty May Hưng Yên - Công ty Cổ phần',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.77,
    yearsTracked: 14,
    description: 'Chuyên may trang phục thời trang xuất khẩu sang các thị trường khó tính như Mỹ, Nhật và EU.',
    keyMarkets: ['Hoa Kỳ', 'EU', 'Nhật Bản'],
  },
  {
    ticker: 'M10',
    name: 'Tổng công ty May 10 - Công ty Cổ phần',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.80,
    yearsTracked: 16,
    description: 'Thương hiệu sơ mi và âu phục xuất khẩu nổi tiếng, thị trường xuất khẩu sang Mỹ, Đức, Nhật Bản.',
    keyMarkets: ['Hoa Kỳ', 'Đức (EU)', 'Nhật Bản'],
  },
  {
    ticker: 'MNB',
    name: 'Tổng Công ty May Nhà Bè - Công ty Cổ phần',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.79,
    yearsTracked: 15,
    description: 'Tập đoàn may mặc quy mô lớn phía Nam, chuyên sản xuất veston và trang phục cao cấp cho các thương hiệu quốc tế.',
    keyMarkets: ['Hoa Kỳ', 'EU', 'Nhật Bản'],
  },
  {
    ticker: 'MPT',
    name: 'Công ty Cổ phần Tập đoàn MPT',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.70,
    yearsTracked: 10,
    description: 'Sản xuất và thương mại sản phẩm dệt may và phụ liệu thời trang.',
    keyMarkets: ['Đông Nam Á', 'Hàn Quốc'],
  },
  {
    ticker: 'PTG',
    name: 'Công ty Cổ phần May Xuất Khẩu Phan Thiết',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.75,
    yearsTracked: 15,
    description: 'Chuyên gia công và sản xuất hàng may mặc xuất khẩu, tỷ suất cổ tức cao và doanh thu ổn định.',
    keyMarkets: ['Hoa Kỳ', 'Châu Âu'],
  },
  {
    ticker: 'TVT',
    name: 'Tổng Công ty Việt Thắng - CTCP',
    exchange: 'HOSE',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may', 'Xơ, sợi dệt các loại', 'Vải các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.78,
    yearsTracked: 16,
    description: 'Sản xuất sợi, dệt vải và may mặc với truyền thống lâu đời, cung ứng nội địa và xuất khẩu trực tiếp.',
    keyMarkets: ['Châu Âu', 'Châu Á'],
  },
  {
    ticker: 'VGG',
    name: 'Tổng Công Ty Cổ phần May Việt Tiến',
    exchange: 'UPCOM',
    groupId: 'det-may',
    groupLabel: 'Dệt may',
    customsCommodities: ['Hàng dệt, may'],
    tradeDirection: 'EXPORT',
    correlationR: 0.83,
    yearsTracked: 16,
    description: 'Một trong những doanh nghiệp may mặc lớn nhất Việt Nam, dẫn đầu xuất khẩu trang phục công sở và casual wear.',
    keyMarkets: ['Hoa Kỳ', 'Nhật Bản', 'EU', 'Hàn Quốc'],
  },

  // --- 3. PHÂN BÓN & HÓA CHẤT (11 mã) ---
  {
    ticker: 'DPM',
    name: 'Tổng Công ty Phân bón và Hóa chất Dầu khí (PVFCCo)',
    exchange: 'HOSE',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại', 'Hóa chất', 'Phân Ure', 'Phân NPK'],
    tradeDirection: 'BOTH',
    correlationR: 0.82,
    yearsTracked: 16,
    description: 'Nhà sản xuất Đạm Phú Mỹ (Ure) hàng đầu Việt Nam, xuất khẩu sang Ấn Độ, Đông Nam Á và nhập khẩu hóa chất, NPK công nghệ cao.',
    keyMarkets: ['Campuchia', 'Ấn Độ', 'Philippines'],
  },
  {
    ticker: 'DCM',
    name: 'Công ty Cổ phần Phân bón Dầu khí Cà Mau (PVCFC)',
    exchange: 'HOSE',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại', 'Phân Ure', 'Phân NPK'],
    tradeDirection: 'BOTH',
    correlationR: 0.84,
    yearsTracked: 15,
    description: 'Nhà sản xuất Đạm Cà Mau, dẫn đầu xuất khẩu phân bón sang Campuchia, Myanmar, Ấn Độ và Nam Mỹ.',
    keyMarkets: ['Campuchia', 'Ấn Độ', 'Brazil', 'Thái Lan'],
  },
  {
    ticker: 'BFC',
    name: 'Công ty Cổ phần Phân bón Bình Điền',
    exchange: 'HOSE',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại', 'Phân NPK'],
    tradeDirection: 'BOTH',
    correlationR: 0.77,
    yearsTracked: 16,
    description: 'Dẫn đầu thị phần phân bón NPK Đầu Trâu trong nước và đẩy mạnh xuất khẩu sang Campuchia, Lào, Thái Lan.',
    keyMarkets: ['Campuchia', 'Lào', 'Thái Lan'],
  },
  {
    ticker: 'DDV',
    name: 'Công ty Cổ phần DAP - Vinachem',
    exchange: 'UPCOM',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại', 'Phân DAP', 'Hóa chất'],
    tradeDirection: 'BOTH',
    correlationR: 0.79,
    yearsTracked: 14,
    description: 'Nhà sản xuất phân bón DAP Đình Vũ lớn nhất miền Bắc, doanh thu tương quan chặt với giá phân bón và hóa chất thế giới.',
    keyMarkets: ['Việt Nam', 'Ấn Độ', 'Đông Nam Á'],
  },
  {
    ticker: 'CSV',
    name: 'Công ty Cổ phần Hóa chất Cơ bản miền Nam',
    exchange: 'HOSE',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Hóa chất', 'Sản phẩm hóa chất'],
    tradeDirection: 'BOTH',
    correlationR: 0.76,
    yearsTracked: 16,
    description: 'Sản xuất hóa chất vô cơ cơ bản (Xút-Clo, HCl, H2SO4, PAC, Silicate) phục vụ xuất khẩu và các ngành công nghiệp nội địa.',
    keyMarkets: ['Việt Nam', 'Nhật Bản', 'Đông Nam Á'],
  },
  {
    ticker: 'DHB',
    name: 'Công ty Cổ phần Phân đạm và Hóa chất Hà Bắc',
    exchange: 'UPCOM',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại', 'Phân Ure', 'Hóa chất'],
    tradeDirection: 'BOTH',
    correlationR: 0.75,
    yearsTracked: 16,
    description: 'Nhà máy Đạm Hà Bắc sản xuất phân Ure từ than cám, cung ứng phân đạm cho miền Bắc và xuất khẩu.',
    keyMarkets: ['Việt Nam', 'Campuchia'],
  },
  {
    ticker: 'NFC',
    name: 'Công ty Cổ phần Phân lân Ninh Bình',
    exchange: 'HNX',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại', 'Phân NPK'],
    tradeDirection: 'BOTH',
    correlationR: 0.72,
    yearsTracked: 15,
    description: 'Sản xuất phân lân nung chảy và phân NPK phục vụ nông nghiệp và xuất khẩu sang Nhật Bản, Úc.',
    keyMarkets: ['Nhật Bản', 'Hàn Quốc', 'Úc'],
  },
  {
    ticker: 'PCE',
    name: 'Công ty Cổ phần Phân bón và Hóa chất Dầu khí Miền Trung',
    exchange: 'HNX',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.74,
    yearsTracked: 14,
    description: 'Đơn vị thương mại và phân phối phân bón, hóa chất Phú Mỹ khu vực miền Trung - Tây Nguyên.',
    keyMarkets: ['Khu vực Miền Trung', 'Lào'],
  },
  {
    ticker: 'PMB',
    name: 'Công ty Cổ phần Phân bón và Hóa chất Dầu khí Miền Bắc',
    exchange: 'HNX',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.73,
    yearsTracked: 14,
    description: 'Phân phối phân bón Đạm Phú Mỹ và NPK tại các tỉnh phía Bắc.',
    keyMarkets: ['Khu vực Miền Bắc'],
  },
  {
    ticker: 'PSE',
    name: 'Công ty Cổ phần Phân bón và Hóa chất Dầu khí Đông Nam Bộ',
    exchange: 'HNX',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.74,
    yearsTracked: 14,
    description: 'Phân phối phân bón dầu khí tại thị trường trọng điểm Đông Nam Bộ.',
    keyMarkets: ['Đông Nam Bộ'],
  },
  {
    ticker: 'PSW',
    name: 'Công ty Cổ phần Phân bón và Hóa chất Dầu khí Tây Nam Bộ',
    exchange: 'HNX',
    groupId: 'phan-bon',
    groupLabel: 'Phân bón & Hóa chất',
    customsCommodities: ['Phân bón các loại'],
    tradeDirection: 'BOTH',
    correlationR: 0.75,
    yearsTracked: 14,
    description: 'Phân phối phân bón tại vựa lúa Đồng bằng Sông Cửu Long và hỗ trợ xuất khẩu biên mậu sang Campuchia.',
    keyMarkets: ['Tây Nam Bộ', 'Campuchia'],
  },

  // --- 4. SẮT THÉP & KIM LOẠI (10 mã) ---
  {
    ticker: 'HPG',
    name: 'Công ty Cổ phần Tập đoàn Hòa Phát',
    exchange: 'HOSE',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Sản phẩm từ sắt thép', 'Phôi thép', 'Quặng và khoáng sản khác'],
    tradeDirection: 'BOTH',
    correlationR: 0.86,
    yearsTracked: 16,
    description: 'Nhà sản xuất thép lớn nhất Đông Nam Á (Thép xây dựng, HRC, ống thép, tôn mạ). Kim ngạch xuất khẩu và nhập khẩu quặng/than của Hòa Phát chiếm tỷ trọng chi phối trong số liệu TCHQ.',
    keyMarkets: ['EU', 'Hoa Kỳ', 'Đông Nam Á', 'Úc'],
  },
  {
    ticker: 'HSG',
    name: 'Công ty Cổ phần Tập đoàn Hoa Sen',
    exchange: 'HOSE',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Sản phẩm từ sắt thép'],
    tradeDirection: 'BOTH',
    correlationR: 0.83,
    yearsTracked: 16,
    description: 'Dẫn đầu thị phần tôn mạ và ống thép, xuất khẩu tới hơn 87 quốc gia và vùng lãnh thổ (châu Âu, Mỹ, ASEAN).',
    keyMarkets: ['Hoa Kỳ', 'EU', 'ASEAN', 'Trung Đông'],
  },
  {
    ticker: 'NKG',
    name: 'Công ty Cổ phần Thép Nam Kim',
    exchange: 'HOSE',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Sản phẩm từ sắt thép'],
    tradeDirection: 'BOTH',
    correlationR: 0.84,
    yearsTracked: 16,
    description: 'Doanh nghiệp tôn mạ có tỷ trọng doanh thu xuất khẩu trên 60%, đặc biệt bám sát biến động xuất khẩu sắt thép sang châu Âu và Bắc Mỹ.',
    keyMarkets: ['EU', 'Hoa Kỳ', 'Úc', 'ASEAN'],
  },
  {
    ticker: 'SMC',
    name: 'Công ty Cổ phần Đầu tư Thương mại SMC',
    exchange: 'HOSE',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Sản phẩm từ sắt thép'],
    tradeDirection: 'BOTH',
    correlationR: 0.79,
    yearsTracked: 16,
    description: 'Hệ thống gia công cắt xẻ Coil Center và thương mại thép hàng đầu, liên kết chặt chẽ với các nhà máy sản xuất linh kiện và FDI.',
    keyMarkets: ['Việt Nam', 'Nhật Bản', 'Hàn Quốc'],
  },
  {
    ticker: 'POM',
    name: 'Công ty Cổ phần Thép Pomina',
    exchange: 'UPCOM',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Phôi thép'],
    tradeDirection: 'BOTH',
    correlationR: 0.75,
    yearsTracked: 16,
    description: 'Nhà sản xuất phôi thép và thép xây dựng quy mô lớn tại miền Nam.',
    keyMarkets: ['Việt Nam', 'Campuchia'],
  },
  {
    ticker: 'BVG',
    name: 'Công ty Cổ phần Group Bắc Việt',
    exchange: 'UPCOM',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Sản phẩm từ sắt thép'],
    tradeDirection: 'BOTH',
    correlationR: 0.71,
    yearsTracked: 14,
    description: 'Sản xuất và thương mại các sản phẩm cơ khí, thép tấm, thép hình kết cấu.',
    keyMarkets: ['Việt Nam', 'Đông Bắc Á'],
  },
  {
    ticker: 'HMC',
    name: 'Công ty Cổ phần Kim Khí Hà Nội - VNSTEEL',
    exchange: 'HOSE',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Kim loại thường khác và sản phẩm'],
    tradeDirection: 'BOTH',
    correlationR: 0.76,
    yearsTracked: 16,
    description: 'Nhà phân phối thép lớn thuộc VNSTEEL, cung cấp các chủng loại thép xây dựng, thép tấm cán nóng và cán nguội.',
    keyMarkets: ['Khu vực Phía Bắc'],
  },
  {
    ticker: 'TIS',
    name: 'Công ty Cổ phần Gang thép Thái Nguyên (TISCO)',
    exchange: 'UPCOM',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Phôi thép', 'Quặng và khoáng sản khác'],
    tradeDirection: 'BOTH',
    correlationR: 0.78,
    yearsTracked: 16,
    description: 'Cái nôi ngành luyện kim Việt Nam, tự chủ sản xuất từ quặng sắt mỏ Trại Cau đến thép thành phẩm TISCO.',
    keyMarkets: ['Việt Nam', 'Lào', 'Campuchia'],
  },
  {
    ticker: 'TVN',
    name: 'Tổng Công ty Thép Việt Nam - CTCP (VNSTEEL)',
    exchange: 'UPCOM',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Sản phẩm từ sắt thép', 'Phôi thép'],
    tradeDirection: 'BOTH',
    correlationR: 0.81,
    yearsTracked: 16,
    description: 'Tổng công ty quản lý hệ thống các liên doanh và công ty con sản xuất phôi, thép xây dựng, tôn mạ trên cả nước.',
    keyMarkets: ['Toàn quốc', 'Đông Nam Á'],
  },
  {
    ticker: 'VCA',
    name: 'Công ty Cổ phần Thép VICASA - VNSTEEL',
    exchange: 'HOSE',
    groupId: 'sat-thep',
    groupLabel: 'Sắt thép & Kim loại',
    customsCommodities: ['Sắt thép các loại', 'Phôi thép'],
    tradeDirection: 'BOTH',
    correlationR: 0.73,
    yearsTracked: 15,
    description: 'Nhà máy luyện cán thép tại Biên Hòa (Đồng Nai), chuyên thép cuộn và thép thanh vằn xây dựng.',
    keyMarkets: ['Khu vực Phía Nam'],
  },

  // --- 5. CAO SU (8 mã) ---
  {
    ticker: 'PHR',
    name: 'Công ty Cổ phần Cao su Phước Hòa',
    exchange: 'HOSE',
    groupId: 'cao-su',
    groupLabel: 'Cao su',
    customsCommodities: ['Cao su', 'Sản phẩm từ cao su'],
    tradeDirection: 'EXPORT',
    correlationR: 0.74,
    yearsTracked: 16,
    description: 'Doanh nghiệp khai thác, chế biến mủ cao su tự nhiên xuất khẩu hàng đầu, đồng thời phát triển quỹ đất KCN trên nền cao su thanh lý.',
    keyMarkets: ['Trung Quốc', 'Hàn Quốc', 'Ấn Độ'],
  },
  {
    ticker: 'DPR',
    name: 'Công ty Cổ phần Cao su Đồng Phú',
    exchange: 'HOSE',
    groupId: 'cao-su',
    groupLabel: 'Cao su',
    customsCommodities: ['Cao su', 'Sản phẩm từ cao su'],
    tradeDirection: 'EXPORT',
    correlationR: 0.73,
    yearsTracked: 16,
    description: 'Sản xuất các chủng loại mủ SVR CV, SVR L, nệm gối cao su thiên nhiên xuất khẩu sang châu Âu và châu Á.',
    keyMarkets: ['EU', 'Trung Quốc', 'Hàn Quốc'],
  },
  {
    ticker: 'DRI',
    name: 'Công ty Cổ phần Đầu tư Cao su Đắk Lắk',
    exchange: 'UPCOM',
    groupId: 'cao-su',
    groupLabel: 'Cao su',
    customsCommodities: ['Cao su'],
    tradeDirection: 'EXPORT',
    correlationR: 0.72,
    yearsTracked: 14,
    description: 'Quản lý vườn cây cao su năng suất cao tại Lào và Tây Nguyên, toàn bộ mủ cao su chế biến phục vụ xuất khẩu.',
    keyMarkets: ['Trung Quốc', 'EU', 'Ấn Độ'],
  },
  {
    ticker: 'BRR',
    name: 'Công ty Cổ phần Cao su Bà Rịa',
    exchange: 'UPCOM',
    groupId: 'cao-su',
    groupLabel: 'Cao su',
    customsCommodities: ['Cao su'],
    tradeDirection: 'EXPORT',
    correlationR: 0.71,
    yearsTracked: 15,
    description: 'Trồng trọt, thu hoạch mủ và chế biến cao su xuất khẩu chất lượng cao tại Bà Rịa - Vũng Tàu.',
    keyMarkets: ['Trung Quốc', 'ASEAN', 'Đức'],
  },
  {
    ticker: 'HRC',
    name: 'Công ty Cổ phần Cao su Hòa Bình',
    exchange: 'HOSE',
    groupId: 'cao-su',
    groupLabel: 'Cao su',
    customsCommodities: ['Cao su'],
    tradeDirection: 'EXPORT',
    correlationR: 0.70,
    yearsTracked: 15,
    description: 'Khai thác vườn cây cao su và xuất khẩu mủ cao su tiêu chuẩn SVR.',
    keyMarkets: ['Trung Quốc', 'Malaysia'],
  },
  {
    ticker: 'IRC',
    name: 'Công ty Cổ phần Cao su Công nghiệp',
    exchange: 'UPCOM',
    groupId: 'cao-su',
    groupLabel: 'Cao su',
    customsCommodities: ['Cao su', 'Sản phẩm từ cao su'],
    tradeDirection: 'BOTH',
    correlationR: 0.69,
    yearsTracked: 13,
    description: 'Sản xuất các sản phẩm kỹ thuật và phụ tùng từ cao su công nghiệp cung cấp cho các ngành lắp ráp, vận tải.',
    keyMarkets: ['Việt Nam', 'Hàn Quốc'],
  },
  {
    ticker: 'RTB',
    name: 'Công ty Cổ phần Cao su Tân Biên',
    exchange: 'UPCOM',
    groupId: 'cao-su',
    groupLabel: 'Cao su',
    customsCommodities: ['Cao su'],
    tradeDirection: 'EXPORT',
    correlationR: 0.72,
    yearsTracked: 15,
    description: 'Khai thác cao su tại Tây Ninh và dự án vườn cây tại Campuchia, xuất khẩu mủ khối SVR.',
    keyMarkets: ['Trung Quốc', 'Campuchia', 'Ấn Độ'],
  },
  {
    ticker: 'TRC',
    name: 'Công ty Cổ phần Cao su Tây Ninh',
    exchange: 'HOSE',
    groupId: 'cao-su',
    groupLabel: 'Cao su',
    customsCommodities: ['Cao su'],
    tradeDirection: 'EXPORT',
    correlationR: 0.73,
    yearsTracked: 16,
    description: 'Doanh nghiệp cao su thuộc VRG với hiệu quả khai thác cao, xuất khẩu mủ SVR 3L, SVR 10 sang các thị trường lớn.',
    keyMarkets: ['Trung Quốc', 'EU', 'Mỹ'],
  },

  // --- 6. NGÀNH KHÁC (Gỗ, Gạo, Nhựa, Gốm) (4 mã) ---
  {
    ticker: 'GTA',
    name: 'Công ty Cổ phần Chế biến Gỗ Thuận An',
    exchange: 'HOSE',
    groupId: 'khac',
    groupLabel: 'Gỗ & Sản phẩm gỗ',
    customsCommodities: ['Gỗ và sản phẩm gỗ'],
    tradeDirection: 'EXPORT',
    correlationR: 0.76,
    yearsTracked: 15,
    description: 'Chế biến và xuất khẩu đồ gỗ nội thất, gỗ ghép thanh sang thị trường Hoa Kỳ và châu Âu.',
    keyMarkets: ['Hoa Kỳ', 'EU', 'Nhật Bản'],
  },
  {
    ticker: 'LTG',
    name: 'Công ty Cổ phần Tập đoàn Lộc Trời',
    exchange: 'UPCOM',
    groupId: 'khac',
    groupLabel: 'Gạo & Nông nghiệp',
    customsCommodities: ['Gạo', 'Thuốc trừ sâu và nguyên liệu'],
    tradeDirection: 'BOTH',
    correlationR: 0.75,
    yearsTracked: 14,
    description: 'Tập đoàn dịch vụ nông nghiệp và xuất khẩu gạo chất lượng cao (gạo thơm Jasmine, gạo thương hiệu) sang EU, Philippines và châu Phi.',
    keyMarkets: ['EU', 'Philippines', 'Châu Phi', 'Trung Quốc'],
  },
  {
    ticker: 'NHH',
    name: 'Công ty Cổ phần Nhựa Hà Nội',
    exchange: 'HOSE',
    groupId: 'khac',
    groupLabel: 'Sản phẩm nhựa',
    customsCommodities: ['Chất dẻo nguyên liệu (nhựa)', 'Sản phẩm từ chất dẻo'],
    tradeDirection: 'BOTH',
    correlationR: 0.74,
    yearsTracked: 14,
    description: 'Sản xuất linh kiện nhựa kỹ thuật cao cho các tập đoàn ô tô, xe máy, điện tử toàn cầu (Toyota, Honda, Samsung, LG).',
    keyMarkets: ['Việt Nam', 'Nhật Bản', 'Hàn Quốc'],
  },
  {
    ticker: 'TCR',
    name: 'Công ty Cổ phần Công nghiệp Gốm sứ TAICERA',
    exchange: 'HOSE',
    groupId: 'khac',
    groupLabel: 'Sản phẩm gốm, sứ',
    customsCommodities: ['Sản phẩm gốm, sứ'],
    tradeDirection: 'EXPORT',
    correlationR: 0.72,
    yearsTracked: 15,
    description: 'Sản xuất gạch ốp lát granite, gốm sứ cao cấp xuất khẩu sang Đài Loan, ASEAN, Úc và tiêu thụ trong nước.',
    keyMarkets: ['Đài Loan', 'Úc', 'ASEAN'],
  },
]

/** Lấy toàn bộ danh sách mã Tier A */
export function getTierAStocks(): TierAStock[] {
  return TIER_A_STOCKS
}

/** Lấy danh sách các nhóm ngành */
export function getTierAGroups(): TierAGroup[] {
  return TIER_A_GROUPS
}

/** Map tra cứu mã cổ phiếu theo tên mặt hàng Hải quan */
export function getStocksForCustomsCommodity(commodityName: string): TierAStock[] {
  const norm = commodityName.toLowerCase().trim()
  return TIER_A_STOCKS.filter((stock) =>
    stock.customsCommodities.some(
      (c) =>
        c.toLowerCase() === norm ||
        norm.includes(c.toLowerCase()) ||
        c.toLowerCase().includes(norm),
    ),
  )
}
