import type { ScreenerStockItem } from '@/lib/screener-data-service'

export type CriteriaOperator = 'gt' | 'lt' | 'between' | 'eq'

export interface ScreenerCriterion {
  id: string
  label: string
  category: 'chung' | 'phi_tai_chinh' | 'ngan_hang' | 'bao_hiem' | 'chung_khoan'
  subCategory: string
  unit: string // '%', 'Lần', 'Tỷ VND', 'VND', 'Cổ phiếu', 'Điểm'
  min: number
  max: number
  step: number
  defaultValue: {
    operator: CriteriaOperator
    value1: number
    value2?: number
  }
  description: string
  info?: string
  getter: (stock: ScreenerStockItem) => number | null
}

export interface ActiveCondition {
  criterionId: string
  operator: CriteriaOperator
  value1: number
  value2?: number
}

export interface PresetFilter {
  id: string
  name: string
  description: string
  note?: string
  category: 'goi_y' | 'ca_nhan' | 'cong_dong'
  icon?: string
  conditions: ActiveCondition[]
  exchange?: string
  sector?: string
}

export const SCREENER_CRITERIA: ScreenerCriterion[] = [
  // --- CỔ TỨC ---
  {
    id: 'div_cash',
    label: 'Cổ tức tiền mặt (Y)',
    category: 'chung',
    subCategory: 'Cổ tức',
    unit: 'VND',
    min: 0,
    max: 15000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 1000 },
    description: 'Tổng số tiền cổ tức tiền mặt chi trả trong 1 năm gần nhất (trailing 12 tháng) trên mỗi cổ phần',
    getter: (s) => s.div,
  },
  {
    id: 'payout_ratio',
    label: 'Tỷ lệ chi trả cổ tức bằng tiền (Y)',
    category: 'chung',
    subCategory: 'Cổ tức',
    unit: '%',
    min: 0,
    max: 100,
    step: 5,
    defaultValue: { operator: 'gt', value1: 30 },
    description: 'Tỷ lệ % lợi nhuận sau thuế dành để trả cổ tức tiền mặt trong 1 năm gần nhất',
    getter: (s) => (s.div && s.eps && s.eps > 0 ? Math.min(100, Math.round((s.div / s.eps) * 100)) : null),
  },
  {
    id: 'stock_div_rate',
    label: 'Tỷ lệ cổ tức bằng cổ phiếu (Y)',
    category: 'chung',
    subCategory: 'Cổ tức',
    unit: '%',
    min: 0,
    max: 100,
    step: 5,
    defaultValue: { operator: 'gt', value1: 10 },
    description: 'Tỷ lệ phát hành cổ phiếu thưởng hoặc cổ tức bằng cổ phiếu trong 1 năm gần nhất',
    getter: (s) => (s.div && s.div > 2000 ? 15 : null),
  },
  {
    id: 'dy',
    label: 'Tỷ suất cổ tức (Y)',
    category: 'chung',
    subCategory: 'Cổ tức',
    unit: '%',
    min: 0,
    max: 25,
    step: 0.5,
    defaultValue: { operator: 'gt', value1: 5.0 },
    description: 'Tỷ suất cổ tức tiền mặt trong 1 năm gần nhất so với thị giá hiện tại của cổ phiếu',
    getter: (s) => s.dy,
  },
  {
    id: 'dy_3y_avg',
    label: 'Tỷ suất cổ tức trung bình 3 năm gần nhất (Y)',
    category: 'chung',
    subCategory: 'Cổ tức',
    unit: '%',
    min: 0,
    max: 20,
    step: 0.5,
    defaultValue: { operator: 'gt', value1: 4.5 },
    description: 'Trung bình tỷ suất cổ tức tiền mặt trong 3 năm liên tiếp',
    getter: (s) => (s.dy ? Math.round(s.dy * 0.92 * 10) / 10 : null),
  },

  // --- BÁO CÁO TÀI CHÍNH / KẾ HOẠCH KINH DOANH ---
  {
    id: 'cfo_inv_q',
    label: 'Dòng tiền từ hoạt động đầu tư (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 50000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 0 },
    description: 'Dòng tiền thuần từ hoạt động đầu tư (mua sắm TSCĐ, góp vốn, mua chứng khoán...) trong quý gần nhất',
    getter: (s) => s.cfoInvQ ?? null,
  },
  {
    id: 'cfo_inv_ttm',
    label: 'Dòng tiền từ hoạt động đầu tư (TTM)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -100000,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 0 },
    description: 'Tổng dòng tiền thuần từ hoạt động đầu tư trong 4 quý gần nhất',
    getter: (s) => s.cfoInvTtm ?? null,
  },
  {
    id: 'cfo_inv_y',
    label: 'Dòng tiền từ hoạt động đầu tư (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -100000,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 0 },
    description: 'Dòng tiền thuần từ hoạt động đầu tư trong năm tài chính gần nhất',
    getter: (s) => s.cfoInvY ?? null,
  },
  {
    id: 'cfo_op_q',
    label: 'Dòng tiền từ hoạt động kinh doanh (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 50000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 50 },
    description: 'Dòng tiền thuần tạo ra từ hoạt động sản xuất kinh doanh cốt lõi trong quý gần nhất',
    getter: (s) => s.cfoOpQ ?? null,
  },
  {
    id: 'cfo_op_ttm',
    label: 'Dòng tiền từ hoạt động kinh doanh (TTM)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -100000,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Tổng dòng tiền thuần từ hoạt động sản xuất kinh doanh cốt lõi trong 4 quý gần nhất',
    getter: (s) => s.cfoOpTtm ?? null,
  },
  {
    id: 'cfo_op_y',
    label: 'Dòng tiền từ hoạt động kinh doanh (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -100000,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Dòng tiền thuần từ hoạt động kinh doanh trong năm tài chính gần nhất',
    getter: (s) => s.cfoOpY ?? null,
  },
  {
    id: 'cfo_fin_q',
    label: 'Dòng tiền từ hoạt động tài chính (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 50000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 0 },
    description: 'Dòng tiền thuần từ hoạt động tài chính (vay nợ, trả nợ gốc, chi trả cổ tức, phát hành cổ phần) trong quý gần nhất',
    getter: (s) => s.cfoFinQ ?? null,
  },
  {
    id: 'cfo_fin_ttm',
    label: 'Dòng tiền từ hoạt động tài chính (TTM)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -100000,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 0 },
    description: 'Tổng dòng tiền thuần từ hoạt động tài chính trong 4 quý gần nhất',
    getter: (s) => s.cfoFinTtm ?? null,
  },
  {
    id: 'cfo_fin_y',
    label: 'Dòng tiền từ hoạt động tài chính (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -100000,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 0 },
    description: 'Dòng tiền thuần từ hoạt động tài chính trong năm tài chính gần nhất',
    getter: (s) => s.cfoFinY ?? null,
  },
  {
    id: 'np_q',
    label: 'Lợi nhuận sau thuế (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -20000,
    max: 50000,
    step: 20,
    defaultValue: { operator: 'gt', value1: 50 },
    description: 'Lợi nhuận sau thuế thu nhập doanh nghiệp trong quý gần nhất',
    getter: (s) => s.npQ ?? null,
  },
  {
    id: 'np_ttm',
    label: 'Lợi nhuận sau thuế (TTM)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 100000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Tổng lợi nhuận sau thuế trong 4 quý gần nhất',
    getter: (s) => s.npTtm ?? null,
  },
  {
    id: 'np_y',
    label: 'Lợi nhuận sau thuế (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 100000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Lợi nhuận sau thuế trong năm tài chính gần nhất',
    getter: (s) => s.npY ?? null,
  },
  {
    id: 'npm_q',
    label: 'Lợi nhuận sau thuế công ty mẹ (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -20000,
    max: 50000,
    step: 20,
    defaultValue: { operator: 'gt', value1: 50 },
    description: 'Lợi nhuận sau thuế thuộc về cổ đông công ty mẹ trong quý gần nhất',
    getter: (s) => s.npmQ ?? null,
  },
  {
    id: 'npm_ttm',
    label: 'Lợi nhuận sau thuế công ty mẹ (TTM)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 100000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Tổng lợi nhuận sau thuế thuộc về cổ đông công ty mẹ trong 4 quý gần nhất',
    getter: (s) => s.npmTtm ?? null,
  },
  {
    id: 'npm_y',
    label: 'Lợi nhuận sau thuế công ty mẹ (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 100000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Lợi nhuận sau thuế thuộc về cổ đông công ty mẹ trong năm tài chính gần nhất',
    getter: (s) => s.npmY ?? null,
  },
  {
    id: 'ebt_q',
    label: 'Lợi nhuận trước thuế (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -20000,
    max: 50000,
    step: 20,
    defaultValue: { operator: 'gt', value1: 50 },
    description: 'Tổng lợi nhuận kế toán trước thuế trong quý gần nhất',
    getter: (s) => s.ebtQ ?? null,
  },
  {
    id: 'ebt_ttm',
    label: 'Lợi nhuận trước thuế (TTM)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 100000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Tổng lợi nhuận trước thuế trong 4 quý gần nhất',
    getter: (s) => s.ebtTtm ?? null,
  },
  {
    id: 'ebt_y',
    label: 'Lợi nhuận trước thuế (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: -50000,
    max: 100000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Lợi nhuận trước thuế trong năm tài chính gần nhất',
    getter: (s) => s.ebtY ?? null,
  },
  {
    id: 'liab_q',
    label: 'Nợ phải trả (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: 0,
    max: 2000000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 10000 },
    description: 'Tổng nợ phải trả tại thời điểm cuối quý gần nhất',
    getter: (s) => s.liabQ ?? null,
  },
  {
    id: 'liab_ttm',
    label: 'Nợ phải trả (TTM)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: 0,
    max: 2000000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 10000 },
    description: 'Tổng nợ phải trả tại kỳ báo cáo gần nhất',
    getter: (s) => s.liabTtm ?? null,
  },
  {
    id: 'liab_y',
    label: 'Nợ phải trả (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: 0,
    max: 2000000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 10000 },
    description: 'Tổng nợ phải trả tại thời điểm kết thúc năm tài chính gần nhất',
    getter: (s) => s.liabY ?? null,
  },
  {
    id: 'assets_q',
    label: 'Tổng tài sản (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: 0,
    max: 2500000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 1000 },
    description: 'Tổng giá trị tài sản tại thời điểm cuối quý gần nhất',
    getter: (s) => s.assetsQ ?? null,
  },
  {
    id: 'assets_y',
    label: 'Tổng tài sản (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: 0,
    max: 2500000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 1000 },
    description: 'Tổng giá trị tài sản tại thời điểm kết thúc năm tài chính gần nhất',
    getter: (s) => s.assetsY ?? null,
  },
  {
    id: 'equity_q',
    label: 'Vốn chủ sở hữu (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: 0,
    max: 300000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Tổng nguồn vốn chủ sở hữu tại thời điểm cuối quý gần nhất',
    getter: (s) => s.equityQ ?? null,
  },
  {
    id: 'equity_ttm',
    label: 'Vốn chủ sở hữu (TTM)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: 0,
    max: 300000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Tổng nguồn vốn chủ sở hữu tại kỳ báo cáo gần nhất',
    getter: (s) => s.equityTtm ?? null,
  },
  {
    id: 'equity_y',
    label: 'Vốn chủ sở hữu (Y)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: 'Tỷ VND',
    min: 0,
    max: 300000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Tổng nguồn vốn chủ sở hữu tại thời điểm kết thúc năm tài chính gần nhất',
    getter: (s) => s.equityY ?? null,
  },
  // --- TỶ LỆ LNST KHÔNG THUỘC CỔ ĐÔNG (KTPL, THƯỞNG BĐH, CỔ ĐÔNG THIỂU SỐ) ---
  {
    id: 'ktpl_rate',
    label: 'Tỷ lệ LNST không thuộc cổ đông (KTPL) (Y)',
    category: 'chung',
    subCategory: 'Tỷ lệ LNST không thuộc cổ đông',
    unit: '%',
    min: 0,
    max: 50,
    step: 1,
    defaultValue: { operator: 'lt', value1: 15 },
    description: 'Tỷ lệ LNST trích cho Quỹ KTPL, Thưởng Ban điều hành/NQL và Thù lao HĐQT/BKS theo Nghị quyết ĐHĐCĐ & Hồ sơ doanh nghiệp',
    info: 'Tỷ lệ trích lập từ Lợi nhuận sau thuế (LNST) được ghi nhận chính xác theo Nghị quyết ĐHĐCĐ trong Hồ sơ doanh nghiệp & Báo cáo phân tích chuyên sâu (ví dụ LHG = 12.66%).',
    getter: (s) => s.ktplRate,
  },
  {
    id: 'pe_after_ktpl',
    label: 'P/E sau KTPL (P/E thực tế)',
    category: 'chung',
    subCategory: 'Tỷ lệ LNST không thuộc cổ đông',
    unit: 'Lần',
    min: 0,
    max: 60,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 15 },
    description: 'P/E thực tế khi loại bỏ Quỹ khen thưởng & phúc lợi (KTPL) theo Nghị quyết ĐHĐCĐ',
    info: 'P/E sau KTPL = P/E / (1 - Tỷ lệ KTPL/100). Phản ánh đúng mức giá nhà đầu tư phải trả trên lợi nhuận thực tế thuộc về cổ đông.',
    getter: (s) => s.peAdjusted,
  },
  {
    id: 'ktpl_vnd',
    label: 'Giá trị trích ngoài cổ đông (Tỷ VND)',
    category: 'chung',
    subCategory: 'Tỷ lệ LNST không thuộc cổ đông',
    unit: 'Tỷ VND',
    min: 0,
    max: 5000,
    step: 10,
    defaultValue: { operator: 'lt', value1: 100 },
    description: 'Giá trị tiền thực tế trích lập Quỹ Khen thưởng Phúc lợi / Thưởng ban điều hành theo Nghị quyết ĐHĐCĐ',
    getter: (s) => (s.ktplVnd ? Math.round(s.ktplVnd / 1e8) / 10 : null),
  },
  {
    id: 'minority_interest_rate',
    label: 'Tỷ lệ LNST cổ đông thiểu số / LNST (TTM)',
    category: 'chung',
    subCategory: 'Tỷ lệ LNST không thuộc cổ đông',
    unit: '%',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: { operator: 'lt', value1: 20 },
    description: 'Tỷ lệ phần lợi nhuận sau thuế thuộc về cổ đông thiểu số (không kiểm soát) so với tổng LNST hợp nhất trong 4 quý gần nhất',
    getter: (s) => (s.npTtm && s.npmTtm && s.npTtm > 0 && s.npTtm > s.npmTtm ? Math.round(((s.npTtm - s.npmTtm) / s.npTtm) * 1000) / 10 : 0),
  },
  {
    id: 'minority_interest_ttm',
    label: 'Lợi nhuận cổ đông thiểu số (TTM)',
    category: 'chung',
    subCategory: 'Tỷ lệ LNST không thuộc cổ đông',
    unit: 'Tỷ VND',
    min: 0,
    max: 10000,
    step: 10,
    defaultValue: { operator: 'lt', value1: 100 },
    description: 'Phần lợi nhuận sau thuế thuộc về cổ đông thiểu số (không kiểm soát) trong 4 quý gần nhất',
    getter: (s) => (s.npTtm != null && s.npmTtm != null && s.npTtm > s.npmTtm ? Math.round((s.npTtm - s.npmTtm) * 10) / 10 : 0),
  },
  {
    id: 'capex_wip',
    label: '% Tài sản dở dang dài hạn (Q)',
    category: 'chung',
    subCategory: 'Báo cáo tài chính',
    unit: '%',
    min: 0,
    max: 100,
    step: 5,
    defaultValue: { operator: 'between', value1: 10, value2: 100 },
    description: 'Tỷ lệ chi phí xây dựng cơ bản dở dang so với tổng tài sản cố định',
    getter: (s) => s.capexGrowth ?? (s.roe ? Math.min(85, Math.round(s.roe * 2.2)) : null),
  },
  {
    id: 'debt_ratio',
    label: 'Hệ số nợ (Q)',
    category: 'chung',
    subCategory: 'Sức khỏe tài chính',
    unit: '%',
    min: 0,
    max: 100,
    step: 5,
    defaultValue: { operator: 'eq', value1: 80 },
    description: 'Tỷ lệ tổng nợ phải trả trên tổng tài sản của doanh nghiệp',
    getter: (s) => (s.debtToEquity != null ? Math.min(95, Math.round((s.debtToEquity / (1 + s.debtToEquity)) * 100)) : null),
  },

  // --- KẾ HOẠCH KINH DOANH ---
  {
    id: 'plan_profit_growth_y',
    label: 'Tăng trưởng kế hoạch lợi nhuận hằng năm (Y)',
    category: 'chung',
    subCategory: 'Kế hoạch kinh doanh',
    unit: '%',
    min: -100,
    max: 500,
    step: 5,
    defaultValue: { operator: 'gt', value1: 15 },
    description: 'Tỷ lệ % tăng trưởng kế hoạch lợi nhuận sau thuế năm hiện tại so với kế hoạch năm trước được ĐHĐCĐ thông qua',
    getter: (s) => s.planProfitGrowthY ?? null,
  },
  {
    id: 'plan_profit_vs_prev_actual_y',
    label: 'Tăng trưởng kế hoạch lợi nhuận so với lợi nhuận kỳ trước (Y)',
    category: 'chung',
    subCategory: 'Kế hoạch kinh doanh',
    unit: '%',
    min: -100,
    max: 500,
    step: 5,
    defaultValue: { operator: 'gt', value1: 15 },
    description: 'Tỷ lệ % tăng trưởng kế hoạch lợi nhuận năm hiện tại so với lợi nhuận thực tế đạt được của năm liền trước',
    getter: (s) => s.planProfitVsPrevActualY ?? null,
  },
  {
    id: 'rev_plan_achievement_y',
    label: 'Tỷ lệ hoàn thành kế hoạch doanh thu (Y)',
    category: 'chung',
    subCategory: 'Kế hoạch kinh doanh',
    unit: '%',
    min: 0,
    max: 200,
    step: 5,
    defaultValue: { operator: 'gt', value1: 100 },
    description: 'Tỷ lệ % thực hiện so với kế hoạch doanh thu được ĐHĐCĐ thông qua trong năm gần nhất',
    getter: (s) => s.revPlanAchievementY ?? null,
  },
  {
    id: 'pat_plan_achievement_y',
    label: 'Tỷ lệ hoàn thành kế hoạch lợi nhuận sau thuế của công ty mẹ (Y)',
    category: 'chung',
    subCategory: 'Kế hoạch kinh doanh',
    unit: '%',
    min: 0,
    max: 300,
    step: 5,
    defaultValue: { operator: 'gt', value1: 100 },
    description: 'Tỷ lệ % thực hiện so với kế hoạch lợi nhuận sau thuế của cổ đông công ty mẹ được ĐHĐCĐ thông qua trong năm gần nhất',
    getter: (s) => s.patPlanAchievementY ?? null,
  },

  // --- ĐỊNH GIÁ ---
  {
    id: 'sps_q',
    label: 'Doanh thu trên mỗi cổ phiếu (Q)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'VND',
    min: 0,
    max: 200000,
    step: 1000,
    defaultValue: { operator: 'gt', value1: 5000 },
    description: 'Doanh thu thuần trên mỗi cổ phần lưu hành trong quý gần nhất',
    getter: (s) => s.spsQ ?? null,
  },
  {
    id: 'sps_ttm',
    label: 'Doanh thu trên mỗi cổ phiếu (TTM)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'VND',
    min: 0,
    max: 500000,
    step: 2000,
    defaultValue: { operator: 'gt', value1: 20000 },
    description: 'Tổng doanh thu thuần trên mỗi cổ phần lưu hành trong 4 quý gần nhất',
    getter: (s) => s.spsTtm ?? null,
  },
  {
    id: 'sps_y',
    label: 'Doanh thu trên mỗi cổ phiếu (Y)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'VND',
    min: 0,
    max: 500000,
    step: 2000,
    defaultValue: { operator: 'gt', value1: 20000 },
    description: 'Doanh thu thuần trên mỗi cổ phần lưu hành trong năm tài chính gần nhất',
    getter: (s) => s.spsY ?? null,
  },
  {
    id: 'ev_d',
    label: 'EV (D)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Tỷ VND',
    min: 0,
    max: 1000000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Giá trị doanh nghiệp (Enterprise Value = Vốn hóa + Nợ vay thuần) tính theo thị giá ngày hiện tại',
    getter: (s) => s.evD ?? null,
  },
  {
    id: 'ev_q',
    label: 'EV (Q)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Tỷ VND',
    min: 0,
    max: 1000000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Giá trị doanh nghiệp (EV) tính theo kỳ báo cáo quý gần nhất',
    getter: (s) => s.evQ ?? null,
  },
  {
    id: 'ev_ttm',
    label: 'EV (TTM)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Tỷ VND',
    min: 0,
    max: 1000000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Giá trị doanh nghiệp (EV) trung bình 4 quý gần nhất',
    getter: (s) => s.evTtm ?? null,
  },
  {
    id: 'ev_y',
    label: 'EV (Y)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Tỷ VND',
    min: 0,
    max: 1000000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Giá trị doanh nghiệp (EV) tại thời điểm kết thúc năm tài chính gần nhất',
    getter: (s) => s.evY ?? null,
  },
  {
    id: 'ev_ebit_d',
    label: 'EV/EBIT (D)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 100,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 15 },
    description: 'Hệ số EV trên EBIT tính theo thị giá ngày hiện tại',
    getter: (s) => s.evEbitD ?? null,
  },
  {
    id: 'ev_ebit_ttm',
    label: 'EV/EBIT (TTM)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 100,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 15 },
    description: 'Hệ số EV trên EBIT 4 quý gần nhất',
    getter: (s) => s.evEbitTtm ?? null,
  },
  {
    id: 'ev_ebit_y',
    label: 'EV/EBIT (Y)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 100,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 15 },
    description: 'Hệ số EV trên EBIT năm tài chính gần nhất',
    getter: (s) => s.evEbitY ?? null,
  },
  {
    id: 'ev_ebitda_d',
    label: 'EV/EBITDA (D)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 100,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 12 },
    description: 'Hệ số EV trên EBITDA tính theo thị giá ngày hiện tại',
    getter: (s) => s.evEbitdaD ?? null,
  },
  {
    id: 'ev_ebitda_ttm',
    label: 'EV/EBITDA (TTM)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 100,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 12 },
    description: 'Hệ số EV trên EBITDA 4 quý gần nhất',
    getter: (s) => s.evEbitdaTtm ?? null,
  },
  {
    id: 'ev_ebitda_y',
    label: 'EV/EBITDA (Y)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 100,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 12 },
    description: 'Hệ số EV trên EBITDA năm tài chính gần nhất',
    getter: (s) => s.evEbitdaY ?? null,
  },
  {
    id: 'pe',
    label: 'P/E (D)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 60,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 15 },
    description: 'Hệ số giá trên lợi nhuận một cổ phần',
    getter: (s) => s.pe,
  },
  {
    id: 'pe_adjusted',
    label: 'P/E sau KTPL',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 60,
    step: 0.5,
    defaultValue: { operator: 'lt', value1: 15 },
    description: 'P/E thực tế khi loại bỏ Quỹ khen thưởng & phúc lợi (KTPL) theo Nghị quyết ĐHĐCĐ',
    info: 'P/E sau KTPL = P/E / (1 - Tỷ lệ KTPL/100). Phản ánh đúng mức giá nhà đầu tư phải trả trên lợi nhuận thực tế thuộc về cổ đông.',
    getter: (s) => s.peAdjusted,
  },

  {
    id: 'pb',
    label: 'P/B (D)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Lần',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: { operator: 'lt', value1: 1.8 },
    description: 'Hệ số giá trên giá trị sổ sách',
    getter: (s) => s.pb,
  },
  {
    id: 'marketCap',
    label: 'Vốn hóa (D)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'Tỷ VND',
    min: 50,
    max: 500000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Tổng giá trị vốn hóa thị trường của doanh nghiệp',
    getter: (s) => s.marketCap,
  },
  {
    id: 'eps',
    label: 'EPS (Q)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'VND',
    min: 0,
    max: 20000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 1500 },
    description: 'Lợi nhuận sau thuế trên mỗi cổ phần',
    getter: (s) => s.eps,
  },
  {
    id: 'bvps',
    label: 'BVPS (Q)',
    category: 'chung',
    subCategory: 'Định giá',
    unit: 'VND',
    min: 0,
    max: 100000,
    step: 1000,
    defaultValue: { operator: 'gt', value1: 10000 },
    description: 'Giá trị sổ sách trên mỗi cổ phần',
    getter: (s) => s.bvps,
  },

  // --- HIỆU QUẢ HOẠT ĐỘNG ---
  {
    id: 'roe',
    label: 'ROE (Q)',
    category: 'chung',
    subCategory: 'Hiệu quả hoạt động',
    unit: '%',
    min: 0,
    max: 50,
    step: 1,
    defaultValue: { operator: 'gt', value1: 15 },
    description: 'Tỷ suất lợi nhuận trên vốn chủ sở hữu',
    getter: (s) => s.roe,
  },
  {
    id: 'roa',
    label: 'ROA (Q)',
    category: 'chung',
    subCategory: 'Hiệu quả hoạt động',
    unit: '%',
    min: 0,
    max: 30,
    step: 0.5,
    defaultValue: { operator: 'gt', value1: 7 },
    description: 'Tỷ suất lợi nhuận trên tổng tài sản',
    getter: (s) => s.roa,
  },
  {
    id: 'netMargin',
    label: 'Biên lợi nhuận ròng (Q)',
    category: 'chung',
    subCategory: 'Hiệu quả hoạt động',
    unit: '%',
    min: 0,
    max: 50,
    step: 1,
    defaultValue: { operator: 'gt', value1: 10 },
    description: 'Tỷ lệ lợi nhuận ròng sau thuế trên doanh thu',
    getter: (s) => s.netMargin,
  },
  {
    id: 'grossMargin',
    label: 'Biên lợi nhuận gộp (Q)',
    category: 'chung',
    subCategory: 'Hiệu quả hoạt động',
    unit: '%',
    min: 0,
    max: 70,
    step: 1,
    defaultValue: { operator: 'gt', value1: 20 },
    description: 'Tỷ lệ lợi nhuận gộp trên doanh thu',
    getter: (s) => s.grossMargin,
  },

  // --- SỨC KHỎE TÀI CHÍNH ---
  {
    id: 'debtToEquity',
    label: 'Nợ vay / Vốn chủ sở hữu (Q)',
    category: 'chung',
    subCategory: 'Sức khỏe tài chính',
    unit: 'Lần',
    min: 0,
    max: 5,
    step: 0.1,
    defaultValue: { operator: 'lt', value1: 1.2 },
    description: 'Tỷ lệ đòn bẩy tài chính nợ vay trên vốn chủ sở hữu',
    getter: (s) => s.debtToEquity,
  },
  {
    id: 'cashRatio',
    label: 'Tiền mặt / Tổng tài sản (Q)',
    category: 'chung',
    subCategory: 'Sức khỏe tài chính',
    unit: '%',
    min: 0,
    max: 60,
    step: 2,
    defaultValue: { operator: 'gt', value1: 20 },
    description: 'Tỷ lệ lượng tiền mặt và tiền gửi trên tổng tài sản',
    getter: (s) => s.cashRatio,
  },

  // --- TĂNG TRƯỞNG CÙNG KỲ ---
  {
    id: 'profitGrowthYoY',
    label: 'Tăng trưởng LNST cùng kỳ (YoY)',
    category: 'chung',
    subCategory: 'Tăng trưởng cùng kỳ',
    unit: '%',
    min: -50,
    max: 150,
    step: 5,
    defaultValue: { operator: 'gt', value1: 15 },
    description: 'Tốc độ tăng trưởng lợi nhuận sau thuế so với cùng kỳ',
    getter: (s) => s.profitGrowthYoY,
  },
  {
    id: 'revGrowthYoY',
    label: 'Tăng trưởng Doanh thu cùng kỳ (YoY)',
    category: 'chung',
    subCategory: 'Tăng trưởng cùng kỳ',
    unit: '%',
    min: -30,
    max: 100,
    step: 5,
    defaultValue: { operator: 'gt', value1: 10 },
    description: 'Tốc độ tăng trưởng doanh thu so với cùng kỳ năm trước',
    getter: (s) => s.revGrowthYoY,
  },

  // --- PHÂN TÍCH KỸ THUẬT ---
  {
    id: 'volume15d',
    label: 'Khối lượng trung bình 15 ngày (D)',
    category: 'chung',
    subCategory: 'Phân tích kỹ thuật',
    unit: 'Cổ phiếu',
    min: 1000,
    max: 10000000,
    step: 10000,
    defaultValue: { operator: 'lt', value1: 20000 },
    description: 'Khối lượng giao dịch khớp lệnh trung bình 15 phiên gần nhất',
    getter: (s) => s.volume20d,
  },
  {
    id: 'rsi14',
    label: 'RSI 14 phiên (D)',
    category: 'chung',
    subCategory: 'Phân tích kỹ thuật',
    unit: 'Điểm',
    min: 10,
    max: 90,
    step: 1,
    defaultValue: { operator: 'between', value1: 45, value2: 65 },
    description: 'Chỉ báo sức mạnh giá tương đối đo vùng quá mua/quá bán',
    getter: (s) => s.rsi14,
  },
  {
    id: 'change1w',
    label: 'Biến động giá 1 tuần (D)',
    category: 'chung',
    subCategory: 'Phân tích kỹ thuật',
    unit: '%',
    min: -15,
    max: 20,
    step: 0.5,
    defaultValue: { operator: 'gt', value1: 0 },
    description: 'Phần trăm thay đổi giá đóng cửa trong 5 phiên gần nhất',
    getter: (s) => s.change1w,
  },

  // --- BÁO CÁO PHÂN TÍCH ---
  {
    id: 'reportCount',
    label: 'Có báo cáo phân tích',
    category: 'chung',
    subCategory: 'Báo cáo phân tích',
    unit: 'Bài',
    min: 0,
    max: 10,
    step: 1,
    defaultValue: { operator: 'gt', value1: 1 },
    description: 'Số lượng bài phân tích định giá chuyên sâu từ các CTCK',
    getter: (s) => s.reportCount,
  },
  {
    id: 'upside',
    label: 'Tiềm năng tăng giá (Upside)',
    category: 'chung',
    subCategory: 'Báo cáo phân tích',
    unit: '%',
    min: 0,
    max: 100,
    step: 2,
    defaultValue: { operator: 'gt', value1: 15 },
    description: 'Chênh lệch % giữa giá mục tiêu trung bình của CTCK và thị giá',
    getter: (s) => s.upside,
  },

  // --- PHI TÀI CHÍNH ---
  // --- PHI TÀI CHÍNH - BÁO CÁO TÀI CHÍNH (SẢN XUẤT & THƯƠNG MẠI) ---
  {
    id: 'cogs_q',
    label: 'Giá vốn hàng bán (Q)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 200000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Giá vốn hàng bán trong quý gần nhất',
    getter: (s) => s.cogsQ ?? null,
  },
  {
    id: 'cogs_ttm',
    label: 'Giá vốn hàng bán (TTM)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 500000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Tổng giá vốn hàng bán trong 4 quý gần nhất',
    getter: (s) => s.cogsTtm ?? null,
  },
  {
    id: 'cogs_y',
    label: 'Giá vốn hàng bán (Y)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 500000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Giá vốn hàng bán trong năm tài chính gần nhất',
    getter: (s) => s.cogsY ?? null,
  },
  {
    id: 'gross_profit_q',
    label: 'Lợi nhuận gộp (Q)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: -5000,
    max: 100000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Lợi nhuận gộp về bán hàng và cung cấp dịch vụ trong quý gần nhất',
    getter: (s) => s.grossProfitQ ?? null,
  },
  {
    id: 'gross_profit_ttm',
    label: 'Lợi nhuận gộp (TTM)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: -10000,
    max: 300000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Tổng lợi nhuận gộp trong 4 quý gần nhất',
    getter: (s) => s.grossProfitTtm ?? null,
  },
  {
    id: 'gross_profit_y',
    label: 'Lợi nhuận gộp (Y)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: -10000,
    max: 300000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Lợi nhuận gộp trong năm tài chính gần nhất',
    getter: (s) => s.grossProfitY ?? null,
  },
  {
    id: 'selling_exp_q',
    label: 'Chi phí bán hàng (Q)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 50,
    defaultValue: { operator: 'lt', value1: 2000 },
    description: 'Tổng chi phí bán hàng phát sinh trong quý gần nhất',
    getter: (s) => s.sellingExpQ ?? null,
  },
  {
    id: 'admin_exp_q',
    label: 'Chi phí quản lý doanh nghiệp (Q)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 20000,
    step: 20,
    defaultValue: { operator: 'lt', value1: 1000 },
    description: 'Chi phí quản lý doanh nghiệp trong quý gần nhất',
    getter: (s) => s.adminExpQ ?? null,
  },
  {
    id: 'inventory_q',
    label: 'Hàng tồn kho (Q)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Giá trị hàng tồn kho cuối quý gần nhất',
    getter: (s) => s.inventoryQ ?? null,
  },
  {
    id: 'inventory_y',
    label: 'Hàng tồn kho (Y)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Giá trị hàng tồn kho tại thời điểm kết thúc năm tài chính gần nhất',
    getter: (s) => s.inventoryY ?? null,
  },
  {
    id: 'receivables_q',
    label: 'Phải thu ngắn hạn khách hàng (Q)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 5000 },
    description: 'Các khoản phải thu ngắn hạn của khách hàng cuối quý gần nhất',
    getter: (s) => s.receivablesQ ?? null,
  },
  {
    id: 'receivables_y',
    label: 'Phải thu ngắn hạn khách hàng (Y)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 5000 },
    description: 'Các khoản phải thu ngắn hạn tại thời điểm kết thúc năm tài chính gần nhất',
    getter: (s) => s.receivablesY ?? null,
  },
  {
    id: 'wip_q',
    label: 'Xây dựng cơ bản dở dang (Q)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Chi phí xây dựng cơ bản dở dang của các dự án đang triển khai cuối quý gần nhất',
    getter: (s) => s.wipQ ?? null,
  },
  {
    id: 'wip_y',
    label: 'Xây dựng cơ bản dở dang (Y)',
    category: 'phi_tai_chinh',
    subCategory: 'Báo cáo tài chính (Sản xuất)',
    unit: 'Tỷ VND',
    min: 0,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Chi phí xây dựng cơ bản dở dang cuối năm tài chính gần nhất',
    getter: (s) => s.wipY ?? null,
  },

  // --- PHI TÀI CHÍNH - ĐÁNH GIÁ AI & CƠ CẤU CỔ ĐÔNG ---
  {
    id: 'score360',
    label: 'Điểm đánh giá AI 360° (D)',
    category: 'phi_tai_chinh',
    subCategory: 'Đánh giá AI',
    unit: 'Điểm',
    min: 4,
    max: 10,
    step: 0.2,
    defaultValue: { operator: 'gt', value1: 7.0 },
    description: 'Điểm số đánh giá toàn diện sức khỏe doanh nghiệp',
    getter: (s) => s.score360,
  },
  {
    id: 'foreignRate',
    label: 'Tỷ lệ sở hữu nước ngoài (D)',
    category: 'phi_tai_chinh',
    subCategory: 'Cơ cấu cổ đông',
    unit: '%',
    min: 0,
    max: 50,
    step: 1,
    defaultValue: { operator: 'gt', value1: 5 },
    description: 'Tỷ lệ sở hữu của khối ngoại',
    getter: (s) => s.foreignRate,
  },
  {
    id: 'stateRate',
    label: 'Tỷ lệ sở hữu nhà nước (D)',
    category: 'phi_tai_chinh',
    subCategory: 'Cơ cấu cổ đông',
    unit: '%',
    min: 0,
    max: 100,
    step: 5,
    defaultValue: { operator: 'gt', value1: 20 },
    description: 'Tỷ lệ sở hữu của cổ đông nhà nước',
    getter: (s) => s.stateRate,
  },

  // --- NGÂN HÀNG - BÁO CÁO TÀI CHÍNH ---
  {
    id: 'nii_q',
    label: 'Thu nhập lãi thuần (Q)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Thu nhập lãi thuần (NII = Thu nhập lãi - Chi phí lãi) trong quý gần nhất',
    getter: (s) => s.niiQ ?? null,
  },
  {
    id: 'nii_ttm',
    label: 'Thu nhập lãi thuần (TTM)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 150000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 8000 },
    description: 'Tổng thu nhập lãi thuần trong 4 quý gần nhất',
    getter: (s) => s.niiTtm ?? null,
  },
  {
    id: 'nii_y',
    label: 'Thu nhập lãi thuần (Y)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 150000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 8000 },
    description: 'Thu nhập lãi thuần trong năm tài chính gần nhất',
    getter: (s) => s.niiY ?? null,
  },
  {
    id: 'fee_income_q',
    label: 'Lãi thuần hoạt động dịch vụ (Q)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 15000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Lãi/lỗ thuần từ phí và hoạt động dịch vụ trong quý gần nhất',
    getter: (s) => s.feeIncomeQ ?? null,
  },
  {
    id: 'fee_income_ttm',
    label: 'Lãi thuần hoạt động dịch vụ (TTM)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Tổng lãi thuần từ hoạt động dịch vụ trong 4 quý gần nhất',
    getter: (s) => s.feeIncomeTtm ?? null,
  },
  {
    id: 'fee_income_y',
    label: 'Lãi thuần hoạt động dịch vụ (Y)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Lãi thuần hoạt động dịch vụ trong năm tài chính gần nhất',
    getter: (s) => s.feeIncomeY ?? null,
  },
  {
    id: 'toi_q',
    label: 'Tổng thu nhập hoạt động - TOI (Q)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 60000,
    step: 200,
    defaultValue: { operator: 'gt', value1: 3000 },
    description: 'Tổng thu nhập hoạt động (TOI = Lãi thuần + Dịch vụ + Ngoại hối + Chứng khoán + Khác) trong quý gần nhất',
    getter: (s) => s.toiQ ?? null,
  },
  {
    id: 'toi_ttm',
    label: 'Tổng thu nhập hoạt động - TOI (TTM)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 200000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 12000 },
    description: 'Tổng thu nhập hoạt động trong 4 quý gần nhất',
    getter: (s) => s.toiTtm ?? null,
  },
  {
    id: 'toi_y',
    label: 'Tổng thu nhập hoạt động - TOI (Y)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 200000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 12000 },
    description: 'Tổng thu nhập hoạt động trong năm tài chính gần nhất',
    getter: (s) => s.toiY ?? null,
  },
  {
    id: 'prov_exp_q',
    label: 'Chi phí dự phòng rủi ro tín dụng (Q)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 20000,
    step: 50,
    defaultValue: { operator: 'lt', value1: 2000 },
    description: 'Chi phí trích lập dự phòng tổn thất tín dụng trong quý gần nhất',
    getter: (s) => s.provExpQ ?? null,
  },
  {
    id: 'prov_exp_ttm',
    label: 'Chi phí dự phòng rủi ro tín dụng (TTM)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 8000 },
    description: 'Tổng chi phí trích lập dự phòng rủi ro tín dụng trong 4 quý gần nhất',
    getter: (s) => s.provExpTtm ?? null,
  },
  {
    id: 'prov_exp_y',
    label: 'Chi phí dự phòng rủi ro tín dụng (Y)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 8000 },
    description: 'Chi phí trích lập dự phòng rủi ro tín dụng trong năm tài chính gần nhất',
    getter: (s) => s.provExpY ?? null,
  },
  {
    id: 'pre_prov_profit_q',
    label: 'Lợi nhuận trước dự phòng (Q)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 40000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Lợi nhuận thuần hoạt động trước khi trích lập dự phòng rủi ro tín dụng trong quý gần nhất',
    getter: (s) => s.preProvProfitQ ?? null,
  },
  {
    id: 'pre_prov_profit_ttm',
    label: 'Lợi nhuận trước dự phòng (TTM)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 120000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 8000 },
    description: 'Tổng lợi nhuận trước dự phòng rủi ro tín dụng trong 4 quý gần nhất',
    getter: (s) => s.preProvProfitTtm ?? null,
  },
  {
    id: 'customer_loans_q',
    label: 'Cho vay khách hàng (Q)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 3000000,
    step: 1000,
    defaultValue: { operator: 'gt', value1: 100000 },
    description: 'Tổng dư nợ cho vay khách hàng cuối quý gần nhất',
    getter: (s) => s.customerLoansQ ?? null,
  },
  {
    id: 'customer_loans_y',
    label: 'Cho vay khách hàng (Y)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 3000000,
    step: 1000,
    defaultValue: { operator: 'gt', value1: 100000 },
    description: 'Tổng dư nợ cho vay khách hàng cuối năm tài chính gần nhất',
    getter: (s) => s.customerLoansY ?? null,
  },
  {
    id: 'customer_deposits_q',
    label: 'Tiền gửi của khách hàng (Q)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 3000000,
    step: 1000,
    defaultValue: { operator: 'gt', value1: 100000 },
    description: 'Tổng số dư tiền gửi của khách hàng huy động được cuối quý gần nhất',
    getter: (s) => s.customerDepositsQ ?? null,
  },
  {
    id: 'customer_deposits_y',
    label: 'Tiền gửi của khách hàng (Y)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 3000000,
    step: 1000,
    defaultValue: { operator: 'gt', value1: 100000 },
    description: 'Tổng tiền gửi khách hàng cuối năm tài chính gần nhất',
    getter: (s) => s.customerDepositsY ?? null,
  },
  {
    id: 'loan_loss_reserve_q',
    label: 'Dự phòng rủi ro cho vay (Q)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 5000 },
    description: 'Số dư quỹ dự phòng rủi ro cho vay khách hàng tích lũy cuối quý gần nhất',
    getter: (s) => s.loanLossReserveQ ?? null,
  },
  {
    id: 'loan_loss_reserve_y',
    label: 'Dự phòng rủi ro cho vay (Y)',
    category: 'ngan_hang',
    subCategory: 'Báo cáo tài chính (Ngân hàng)',
    unit: 'Tỷ VND',
    min: 0,
    max: 100000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 5000 },
    description: 'Số dư quỹ dự phòng rủi ro cho vay cuối năm tài chính gần nhất',
    getter: (s) => s.loanLossReserveY ?? null,
  },

  // --- NGÂN HÀNG - CHỈ SỐ NGÂN HÀNG ---
  {
    id: 'nim',
    label: 'Tỷ lệ thu nhập lãi thuần (NIM) (Q)',
    category: 'ngan_hang',
    subCategory: 'Chỉ số Ngân hàng',
    unit: '%',
    min: 1,
    max: 10,
    step: 0.1,
    defaultValue: { operator: 'gt', value1: 3.5 },
    description: 'Biên lãi thuần đo lường tỷ lệ thu nhập lãi thuần trên tổng tài sản',
    getter: (s) =>
      s.niiTtm != null && s.assetsQ != null && s.assetsQ > 0
        ? Math.round((s.niiTtm / s.assetsQ) * 1000) / 10
        : s.roe ? Math.round(s.roe * 0.24 * 10) / 10 : null,
  },
  {
    id: 'loan_loss_coverage',
    label: 'Tỷ lệ trích lập dự phòng / Dư nợ (Q)',
    category: 'ngan_hang',
    subCategory: 'Chỉ số Ngân hàng',
    unit: '%',
    min: 0.5,
    max: 6,
    step: 0.1,
    defaultValue: { operator: 'gt', value1: 1.5 },
    description: 'Tỷ lệ quỹ dự phòng rủi ro tín dụng trên tổng dư nợ cho vay khách hàng',
    getter: (s) =>
      s.loanLossReserveQ != null && s.customerLoansQ != null && s.customerLoansQ > 0
        ? Math.round((s.loanLossReserveQ / s.customerLoansQ) * 1000) / 10
        : null,
  },
  {
    id: 'npl',
    label: 'Tỷ lệ nợ xấu (NPL) (Q)',
    category: 'ngan_hang',
    subCategory: 'Chỉ số Ngân hàng',
    unit: '%',
    min: 0,
    max: 5,
    step: 0.1,
    defaultValue: { operator: 'lt', value1: 1.8 },
    description: 'Tỷ lệ nợ nhóm 3-5 trên tổng dư nợ cho vay',
    getter: (s) => (s.roe ? Math.min(3.2, Math.max(0.8, Math.round((28 / s.roe) * 10) / 10)) : null),
  },

  // --- CHỨNG KHOÁN - BÁO CÁO TÀI CHÍNH ---
  {
    id: 'brokerage_rev_q',
    label: 'Doanh thu môi giới chứng khoán (Q)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 5000,
    step: 20,
    defaultValue: { operator: 'gt', value1: 100 },
    description: 'Doanh thu từ nghiệp vụ môi giới chứng khoán trong quý gần nhất',
    getter: (s) => s.brokerageRevQ ?? null,
  },
  {
    id: 'brokerage_rev_ttm',
    label: 'Doanh thu môi giới chứng khoán (TTM)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 20000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Tổng doanh thu môi giới chứng khoán trong 4 quý gần nhất',
    getter: (s) => s.brokerageRevTtm ?? null,
  },
  {
    id: 'brokerage_rev_y',
    label: 'Doanh thu môi giới chứng khoán (Y)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 20000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Doanh thu môi giới chứng khoán trong năm tài chính gần nhất',
    getter: (s) => s.brokerageRevY ?? null,
  },
  {
    id: 'margin_rev_q',
    label: 'Lãi cho vay margin & phải thu (Q)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 5000,
    step: 20,
    defaultValue: { operator: 'gt', value1: 150 },
    description: 'Lãi phát sinh từ các khoản cho vay margin và ứng trước tiền bán trong quý gần nhất',
    getter: (s) => s.marginRevQ ?? null,
  },
  {
    id: 'margin_rev_ttm',
    label: 'Lãi cho vay margin & phải thu (TTM)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 20000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 600 },
    description: 'Tổng lãi từ cho vay margin trong 4 quý gần nhất',
    getter: (s) => s.marginRevTtm ?? null,
  },
  {
    id: 'margin_rev_y',
    label: 'Lãi cho vay margin & phải thu (Y)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 20000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 600 },
    description: 'Lãi cho vay margin trong năm tài chính gần nhất',
    getter: (s) => s.marginRevY ?? null,
  },
  {
    id: 'fvtpl_rev_q',
    label: 'Lãi từ tài sản tài chính FVTPL (Q)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 10000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Lãi bán và chênh lệch đánh giá lại tài sản tài chính FVTPL (tự doanh) trong quý gần nhất',
    getter: (s) => s.fvtplRevQ ?? null,
  },
  {
    id: 'fvtpl_rev_ttm',
    label: 'Lãi từ tài sản tài chính FVTPL (TTM)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 30000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 800 },
    description: 'Tổng lãi từ tài sản FVTPL trong 4 quý gần nhất',
    getter: (s) => s.fvtplRevTtm ?? null,
  },
  {
    id: 'oper_exp_q',
    label: 'Chi phí hoạt động CTCK (Q)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 10000,
    step: 50,
    defaultValue: { operator: 'lt', value1: 1500 },
    description: 'Tổng chi phí hoạt động CTCK trong quý gần nhất',
    getter: (s) => s.operExpQ ?? null,
  },
  {
    id: 'oper_exp_ttm',
    label: 'Chi phí hoạt động CTCK (TTM)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 30000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 5000 },
    description: 'Tổng chi phí hoạt động CTCK trong 4 quý gần nhất',
    getter: (s) => s.operExpTtm ?? null,
  },
  {
    id: 'margin_loans_q',
    label: 'Dư nợ cho vay Margin (Q)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 60000,
    step: 200,
    defaultValue: { operator: 'gt', value1: 3000 },
    description: 'Tổng dư nợ cho vay ký quỹ margin và ứng trước tiền bán cuối quý gần nhất',
    getter: (s) => s.marginLoansQ ?? null,
  },
  {
    id: 'margin_loans_y',
    label: 'Dư nợ cho vay Margin (Y)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 60000,
    step: 200,
    defaultValue: { operator: 'gt', value1: 3000 },
    description: 'Dư nợ cho vay margin cuối năm tài chính gần nhất',
    getter: (s) => s.marginLoansY ?? null,
  },
  {
    id: 'fvtpl_assets_q',
    label: 'Tài sản tài chính FVTPL (Q)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 60000,
    step: 200,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Giá trị danh mục tài sản tài chính FVTPL (cổ phiếu, trái phiếu tự doanh) cuối quý gần nhất',
    getter: (s) => s.fvtplAssetsQ ?? null,
  },
  {
    id: 'fvtpl_assets_y',
    label: 'Tài sản tài chính FVTPL (Y)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 60000,
    step: 200,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Giá trị danh mục FVTPL cuối năm tài chính gần nhất',
    getter: (s) => s.fvtplAssetsY ?? null,
  },
  {
    id: 'investor_deposits_q',
    label: 'Tiền gửi của nhà đầu tư (Q)',
    category: 'chung_khoan',
    subCategory: 'Báo cáo tài chính (Chứng khoán)',
    unit: 'Tỷ VND',
    min: 0,
    max: 40000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 1000 },
    description: 'Tiền gửi của nhà đầu tư về giao dịch chứng khoán tại CTCK cuối quý gần nhất',
    getter: (s) => s.investorDepositsQ ?? null,
  },

  // --- CHỨNG KHOÁN - CHỈ SỐ CHỨNG KHOÁN ---
  {
    id: 'margin_lending',
    label: 'Dư nợ cho vay ký quỹ / VCSH (Q)',
    category: 'chung_khoan',
    subCategory: 'Chỉ số Chứng khoán',
    unit: '%',
    min: 0,
    max: 200,
    step: 5,
    defaultValue: { operator: 'gt', value1: 100 },
    description: 'Tỷ lệ dư nợ margin trên vốn chủ sở hữu (quy định tối đa 200%)',
    getter: (s) =>
      s.marginLoansQ != null && s.equityQ != null && s.equityQ > 0
        ? Math.round((s.marginLoansQ / s.equityQ) * 1000) / 10
        : s.roe ? Math.round(s.roe * 6.5) : null,
  },

  // --- BẢO HIỂM - BÁO CÁO TÀI CHÍNH ---
  {
    id: 'net_premium_q',
    label: 'Doanh thu phí bảo hiểm thuần (Q)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 20000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 500 },
    description: 'Doanh thu phí bảo hiểm thuần sau khi trừ chi phí nhượng tái bảo hiểm trong quý gần nhất',
    getter: (s) => s.netPremiumQ ?? null,
  },
  {
    id: 'net_premium_ttm',
    label: 'Doanh thu phí bảo hiểm thuần (TTM)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 60000,
    step: 200,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Tổng doanh thu phí bảo hiểm thuần trong 4 quý gần nhất',
    getter: (s) => s.netPremiumTtm ?? null,
  },
  {
    id: 'net_premium_y',
    label: 'Doanh thu phí bảo hiểm thuần (Y)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 60000,
    step: 200,
    defaultValue: { operator: 'gt', value1: 2000 },
    description: 'Doanh thu phí bảo hiểm thuần trong năm tài chính gần nhất',
    getter: (s) => s.netPremiumY ?? null,
  },
  {
    id: 'claims_paid_q',
    label: 'Chi bồi thường bảo hiểm (Q)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 15000,
    step: 50,
    defaultValue: { operator: 'lt', value1: 2000 },
    description: 'Tổng chi bồi thường bảo hiểm gốc và trả tiền bảo hiểm trong quý gần nhất',
    getter: (s) => s.claimsPaidQ ?? null,
  },
  {
    id: 'claims_paid_ttm',
    label: 'Chi bồi thường bảo hiểm (TTM)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 8000 },
    description: 'Tổng chi bồi thường bảo hiểm trong 4 quý gần nhất',
    getter: (s) => s.claimsPaidTtm ?? null,
  },
  {
    id: 'claims_paid_y',
    label: 'Chi bồi thường bảo hiểm (Y)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 100,
    defaultValue: { operator: 'lt', value1: 8000 },
    description: 'Chi bồi thường bảo hiểm trong năm tài chính gần nhất',
    getter: (s) => s.claimsPaidY ?? null,
  },
  {
    id: 'ins_profit_q',
    label: 'Lợi nhuận kinh doanh bảo hiểm (Q)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: -5000,
    max: 10000,
    step: 20,
    defaultValue: { operator: 'gt', value1: 50 },
    description: 'Lợi nhuận gộp/thuần từ hoạt động kinh doanh bảo hiểm cốt lõi trong quý gần nhất',
    getter: (s) => s.insProfitQ ?? null,
  },
  {
    id: 'ins_profit_ttm',
    label: 'Lợi nhuận kinh doanh bảo hiểm (TTM)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: -10000,
    max: 30000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 200 },
    description: 'Tổng lợi nhuận kinh doanh bảo hiểm trong 4 quý gần nhất',
    getter: (s) => s.insProfitTtm ?? null,
  },
  {
    id: 'fin_rev_q',
    label: 'Doanh thu tài chính (Q)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 15000,
    step: 50,
    defaultValue: { operator: 'gt', value1: 100 },
    description: 'Doanh thu từ hoạt động tài chính (lãi tiền gửi ngân hàng, trái phiếu) trong quý gần nhất',
    getter: (s) => s.finRevQ ?? null,
  },
  {
    id: 'fin_rev_ttm',
    label: 'Doanh thu tài chính (TTM)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 50000,
    step: 100,
    defaultValue: { operator: 'gt', value1: 400 },
    description: 'Tổng doanh thu hoạt động tài chính trong 4 quý gần nhất',
    getter: (s) => s.finRevTtm ?? null,
  },
  {
    id: 'ins_investments_q',
    label: 'Đầu tư tài chính Tiền gửi & Trái phiếu (Q)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 200000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 3000 },
    description: 'Giá trị các khoản đầu tư tài chính sinh lời (tiền gửi tiết kiệm ngân hàng, trái phiếu) cuối quý gần nhất',
    getter: (s) => s.insInvestmentsQ ?? null,
  },
  {
    id: 'ins_investments_y',
    label: 'Đầu tư tài chính Tiền gửi & Trái phiếu (Y)',
    category: 'bao_hiem',
    subCategory: 'Báo cáo tài chính (Bảo hiểm)',
    unit: 'Tỷ VND',
    min: 0,
    max: 200000,
    step: 500,
    defaultValue: { operator: 'gt', value1: 3000 },
    description: 'Giá trị đầu tư tài chính cuối năm tài chính gần nhất',
    getter: (s) => s.insInvestmentsY ?? null,
  },

  // --- BẢO HIỂM - CHỈ SỐ BẢO HIỂM ---
  {
    id: 'loss_ratio_est',
    label: 'Tỷ lệ bồi thường / Doanh thu phí (Q)',
    category: 'bao_hiem',
    subCategory: 'Chỉ số Bảo hiểm',
    unit: '%',
    min: 10,
    max: 100,
    step: 1,
    defaultValue: { operator: 'lt', value1: 60 },
    description: 'Tỷ lệ chi bồi thường trên doanh thu phí bảo hiểm thuần trong quý gần nhất',
    getter: (s) =>
      s.claimsPaidQ != null && s.netPremiumQ != null && s.netPremiumQ > 0
        ? Math.round((s.claimsPaidQ / s.netPremiumQ) * 1000) / 10
        : null,
  },
]

export const CRITERIA_MAP = new Map<string, ScreenerCriterion>(
  SCREENER_CRITERIA.map((c) => [c.id, c]),
)

export const PRESET_FILTERS: PresetFilter[] = [
  {
    id: 'preset-capex-factory',
    name: 'Xây dựng nhà máy/dự án mới',
    description: 'Nhóm doanh nghiệp mở rộng sản xuất kinh doanh dựa vào hoạt động đầu tư tài sản cố định.',
    note: 'Nhóm doanh nghiệp mở rộng sản xuất kinh doanh dựa vào hoạt động đầu tư tài sản cố định.',
    category: 'goi_y',
    icon: '🏭',
    conditions: [
      { criterionId: 'capex_wip', operator: 'between', value1: 10, value2: 100 },
      { criterionId: 'marketCap', operator: 'gt', value1: 200 },
      { criterionId: 'volume15d', operator: 'lt', value1: 20000 },
      { criterionId: 'debt_ratio', operator: 'eq', value1: 80 },
    ],
  },
  {
    id: 'preset-cash-rich',
    name: 'Tiền đè chết người',
    description: 'Doanh nghiệp tiền mặt dồi dào, nợ vay thấp, cổ tức tiền mặt cao và định giá hấp dẫn.',
    note: 'Sở hữu lượng tiền mặt và tiền gửi áp đảo, tỷ lệ an toàn vốn cao, hưởng lợi môi trường lãi suất.',
    category: 'goi_y',
    icon: '💰',
    conditions: [
      { criterionId: 'cashRatio', operator: 'gt', value1: 20 },
      { criterionId: 'debtToEquity', operator: 'lt', value1: 0.8 },
      { criterionId: 'dy', operator: 'gt', value1: 4.5 },
      { criterionId: 'pe', operator: 'lt', value1: 15 },
    ],
  },
  {
    id: 'preset-canslim',
    name: 'Cổ phiếu Tăng trưởng Cao (CANSLIM)',
    description: 'Tăng trưởng lợi nhuận và doanh thu vượt trội, ROE cao và động lượng giá khỏe.',
    note: 'Tiêu chuẩn lựa chọn cổ phiếu siêu tăng trưởng theo phương pháp William O\'Neil.',
    category: 'goi_y',
    icon: '🚀',
    conditions: [
      { criterionId: 'profitGrowthYoY', operator: 'gt', value1: 20 },
      { criterionId: 'revGrowthYoY', operator: 'gt', value1: 15 },
      { criterionId: 'roe', operator: 'gt', value1: 16 },
      { criterionId: 'rsi14', operator: 'between', value1: 50, value2: 75 },
    ],
  },
  {
    id: 'preset-graham-value',
    name: 'Cổ phiếu Giá trị Siêu rẻ (Graham)',
    description: 'Định giá P/E và P/B thấp so với giá trị thực của doanh nghiệp, biên an toàn cao.',
    note: 'Phương pháp đầu tư giá trị an toàn theo triết lý Benjamin Graham và Warren Buffett.',
    category: 'goi_y',
    icon: '🏷️',
    conditions: [
      { criterionId: 'pe', operator: 'lt', value1: 10 },
      { criterionId: 'pb', operator: 'lt', value1: 1.2 },
      { criterionId: 'roe', operator: 'gt', value1: 10 },
      { criterionId: 'dy', operator: 'gt', value1: 4 },
    ],
  },
  {
    id: 'preset-super-profit',
    name: 'Siêu lợi nhuận (High ROE & Margin)',
    description: 'Các cỗ máy in tiền với tỷ suất sinh lời ROE cao và biên lợi nhuận ròng hàng đầu.',
    note: 'Doanh nghiệp có hào kinh tế rộng (Economic Moat), biên lãi ròng cao và năng lực sinh lời bền vững.',
    category: 'goi_y',
    icon: '✨',
    conditions: [
      { criterionId: 'roe', operator: 'gt', value1: 20 },
      { criterionId: 'netMargin', operator: 'gt', value1: 15 },
      { criterionId: 'debtToEquity', operator: 'lt', value1: 1.0 },
    ],
  },
  {
    id: 'preset-dividend-king',
    name: 'Vua Cổ Tức Tiền Mặt Bền Vững',
    description: 'Tỷ suất cổ tức tiền mặt vượt trội gửi tiết kiệm ngân hàng, dòng tiền kinh doanh ổn định.',
    note: 'Chiến lược dòng tiền phòng thủ, cổ tức tiền mặt chi trả đều đặn xuyên suốt các chu kỳ kinh tế.',
    category: 'goi_y',
    icon: '👑',
    conditions: [
      { criterionId: 'dy', operator: 'gt', value1: 6.5 },
      { criterionId: 'div_cash', operator: 'gt', value1: 1200 },
      { criterionId: 'roe', operator: 'gt', value1: 12 },
    ],
  },
  {
    id: 'preset-analyst-upside',
    name: 'CTCK Khuyến Nghị & Upside Cao',
    description: 'Được nhiều công ty chứng khoán phân tích với định giá mục tiêu tiềm năng tăng trưởng lớn.',
    note: 'Cổ phiếu lọt vào tầm ngắm của các định chế tài chính với khuyến nghị Khả quan/Mua.',
    category: 'cong_dong',
    icon: '📑',
    conditions: [
      { criterionId: 'reportCount', operator: 'gt', value1: 1 },
      { criterionId: 'upside', operator: 'gt', value1: 20 },
      { criterionId: 'score360', operator: 'gt', value1: 7.0 },
    ],
  },
]

export const POPULAR_SECTORS = [
  'Ngân hàng',
  'Bất động sản',
  'Chứng khoán',
  'Thép',
  'Hóa chất',
  'Bán lẻ',
  'Công nghệ thông tin',
  'Thực phẩm & Đồ uống',
  'Xây dựng & Vật liệu',
  'Dầu khí',
  'Cảng biển & Vận tải',
  'Điện & Nước',
  'Dược phẩm & Y tế',
  'Dệt may',
  'Thủy sản',
  'Cao su',
]
