import { NextResponse } from "next/server";

const REPORTS = [
  {
    slug: "snz-q2-2026",
    ticker: "SNZ",
    title: "Đánh Giá Tài Sản SNZ Tính RNAV",
    category: "RNAV",
    date: "2026-08-08",
    driveDocId: "1t_KeRA3vDInpaXUjLDZENM8taoiMJFYT5DvwE0evaV8",
  },
  {
    slug: "bmi-q2-2026",
    ticker: "BMI",
    title: "Định Giá Cổ Phiếu BMI",
    category: "Bảo Hiểm",
    date: "2026-07-31",
    driveDocId: "1yjHgV9ubhIOZbkkfZGlLLCcqRXzc15-5Gxsvl-SCD8E",
  },
  {
    slug: "sgp-q2-2026",
    ticker: "SGP",
    title: "Định Giá Cổ Phiếu SGP - Cảng Sài Gòn",
    category: "Cảng Biển",
    date: "2026-07-14",
    driveDocId: "1k4IGwsmxdt7BUNYceBfUuZ27r_eeKjczPw11T0kT3QM",
  },
  {
    slug: "szl-q2-2026",
    ticker: "SZL",
    title: "Định Giá Cổ Phiếu SZL Bằng RNAV",
    category: "RNAV",
    date: "2026-04-12",
    driveDocId: "1gElWhAi1znQTnhKOS-v_MEK6nOoaVyNml8v-33UARTA",
  },
  {
    slug: "ttt-q2-2026",
    ticker: "TTT",
    title: "Định Giá Cổ Phiếu TTT",
    category: "Định Giá Doanh Nghiệp",
    date: "2026-07-13",
    driveDocId: "1YwOp6RG6Yxk9jnpwWmLtpld_EWnYapUfYMKeTZ0EbKE",
  },
  {
    slug: "vnf-q2-2026",
    ticker: "VNF",
    title: "Định Giá Cổ Phiếu VNF - Vinafreight",
    category: "CTY Liên Kết",
    date: "2026-08-01",
    driveDocId: "1jSk0lAOqaMh9Z4ThFcqRNlDCAwWX9cnlcoJs0y3PVGs",
  },
  {
    slug: "vnl-q2-2026",
    ticker: "VNL",
    title: "Định Giá Cổ Phiếu VNL - Logistics",
    category: "Logistics",
    date: "2026-08-01",
    driveDocId: "19iuzCYO1KwtH3tpU2iefRtMFetgjonD9V-vJ9o2J3gw",
  },
  {
    slug: "dri-q2-2026",
    ticker: "DRI",
    title: "Định Giá DRI Theo RNAV Chi Tiết",
    category: "RNAV",
    date: "2026-04-23",
    driveDocId: "1VqDyBRY33phdQCchleO9KZmZ_krgWezrhFz6lmHOekg",
  },
  {
    slug: "lhg-q2-2026",
    ticker: "LHG",
    title: "Định Giá LHG Theo Phương Pháp RNAV",
    category: "RNAV",
    date: "2026-05-22",
    driveDocId: "1LTbiMCRZHNPS31XZTN2BPpRgywc51bEbnRVuAlIgMQ8",
  },
  {
    slug: "m10-q2-2026",
    ticker: "M10",
    title: "Định Giá M10 Và Tiềm Năng Tăng Trưởng",
    category: "Dệt May",
    date: "2026-04-29",
    driveDocId: "1iwA-9XQossagjnpk1chEIZaM6bkXiY_EeND27wIY430",
  },
  {
    slug: "ral-q2-2026",
    ticker: "RAL",
    title: "Định Giá RAL Và Phân Tích Tăng Trưởng",
    category: "Sản Xuất",
    date: "2026-05-02",
    driveDocId: "1rVEdcwplN-FUDrNJjXYj3Ed3DgHLIgKEq6oZRk-Yn3c",
  },
  {
    slug: "sd9-q2-2026",
    ticker: "SD9",
    title: "Định Giá RNAV Của SD9",
    category: "RNAV",
    date: "2026-08-07",
    driveDocId: "1vbjd1GF8gTkUp4ptUYGtm7JsURm85d1v9B8SeQ5hmf0",
  },
  {
    slug: "idv-q2-2026",
    ticker: "IDV",
    title: "Deep Research IDV - Phân Tích RNAV 2026",
    category: "RNAV",
    date: "2026-08-08",
    driveDocId: "1ua3L_bcAqwpz-0soIg8GetncvQ_MAQtP-7NOXVYXvtg",
  },
  {
    slug: "dc4-q2-2026",
    ticker: "DC4",
    title: "Phân Tích Cổ Phiếu DC4 & Quỹ Đất DICERA",
    category: "Bất Động Sản",
    date: "2026-08-08",
    driveDocId: "1Z3FIe3ExzMBLCJEU-AKjo1Rso_e581u0_lfkHEKXRt0",
  },
];

export async function GET() {
  return NextResponse.json(REPORTS);
}
